from __future__ import annotations

import asyncio
import base64
import io
import os
from datetime import date
from html import escape
from typing import Any, Dict, List, Optional, Tuple

import streamlit.components.v1 as components
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import Image, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

PRIMARY = "#00DC8E"
CYAN = "#CBF9F9"
YELLOW = "#FFCC33"
RED = "#FF6B6B"
GRAY = "#808080"
DARK = "#5F6368"
BORDER = "#9EB3B3"
WHITE = "#FFFFFF"

# Silueta extraída de la referencia entregada por el cliente.
# Es decorativa; los gráficos y datos se generan dinámicamente.
BODY_SILHOUETTE_B64 = "iVBORw0KGgoAAAANSUhEUgAAAdQAAAPrCAYAAADhlH09AAAeQUlEQVR4nO3dWZYTuRqFUVOLoTBCBsIImQv34dJk53Q44qj7tfdjLSjssKRPinDC7QYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADA/L6MfgEAt9vtdvv549e7//btuzWKZfw3+gUAfEhMWYygAnMQUBYnqMB8xBUALvroWSoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACc8WX0CwA+8PPHr1O/79t3cxoGMflgpLPhfJbQQnMmGfTUK6CPCCzEmVTQ2iwRvUdcIcJEglZmD+lbwgqXmECQtlpI3xJWOMXEgZTVQ/qWsMJT/hv9AqCEajG93Wq+J2jIDhSu2CU6TqvwkBMqnLVLTG+3vd4rnCSocMaOgdnxPcMTBBWetXNYdn7v8ICgwjMExTWAOwQVjhKSf1wLeEdQ4QgBAR4QVOAcmwx4RVDhEeG4z7WBvwQVPiMYwEGCClxj0wG3201Q4T6hOM61AkEFgARBhY84cT3PNWNzggoAAYIKAAGCCm+5dXmea8fGBBUAAgQVXnLCAk4SVCDLpoRNCSoABAgq/OFkBVwgqECezQkbElQACBBUAAgQVAAIEFQACBBUuN18iQa4TFCBNmxS2IygAkCAoAJAgKACQICgAkCAoAJAgKACQICgAkCAoAJAgKACQICgAkCAoAJAgKACQICgAkCAoAJAgKACQICgAkCAoAJAgKDC7Xa7ffv+ZfRLKMc1ZTOCCgABggoAAYIKAAGCCgABggoAAb6Fx75+/vg1+iVsxbd+Kc4JlT2JaX+uOcUJKtCPqFKYoLIfizrQgKACQICgAkCAoAJAgKACQICgAkCAoAJAgKACQICgAkCAoAJAgKACQICgsh//6gnQgKAC/djMUJigAkCAoAJAgKACQICgAkCAoLInX47pzzWnOEEFgABBBdpzOmUDgsq+LPJAkKACQICgsjen1PZcYzYhqGDBb8e1ZSOCCrQhpmxGUOF2s/gDlwkq/CGqOa4lGxJUeEkIrnMN2ZSgwluCcJ5rx8YMfvjMzx+/Rr+EJQgpOKHCp4TiMdcIbreboAJAhKDCI05g97k28JegAkCAoAJAgKACQICgwhGeFb7nmsArggoAAYIKAAGCCgABggpHeWb4j2sB7wgqAAQIKjzDyQy4Q1CB59hUwIcEFZ4lKMAHBBU4zmYC7hJUOENYgDcEFc7aLaq7vV94kqACj4kpPCSocIXQAL8JKvA5mwY4RFABIEBQASBAUAEgQFABIEBQASBAUAEgQFABIEBQASBAUAEgQFABIEBQASBAUAEgQFABIEBQASBAUAEgQFABIEBQASBAUAEgQFABIEBQASBAUIHP/fzxa/RLgBUIKgAECCoABAgqXOF2KPCboAJAgKACjzmJw0OCCgABggpnObUBLwgqcIwNBHxKUOEMcQHeEFTgOBsJuEtQ4Vm7R2X39w93CCo8Q0yAOwQVjhLTf1wLeEdQ4QgBec81gVcEFR4RjvtcG/jry+gXANMSi+O+fbeWsD2TAD4ipucIKxtzyxfeEtPzXDs2JqjwkiBc5xqyKUGFP4Qgx7VkQ553gMW/Lc9V2YQTKnsT0/ZcYzZh58ieLPL9OalSnAHOfsR0LGGlKLd82YuYjuczoCg7RfZgEZ+T0yqFGMzUJ6bzE1YKMIipS0jXIqoszgCmHiFdm7CyKAOXOoS0FmFlMQYs6xPS2oSVRRiorEtI9yKsTM4AZT1CujdhZVIGJusQUl4SViZjQDI3EeUIcWUCBiFzElLOEFYGMviYi5CSIq50ZsAxnojSkrDSiYFGfwLKSAJLIwYWfYgoMxJXggwm2hFRViKuXGQAkSWiVCCunGDQkCGkVCSsPMFg4RohZRfiygMGCOcIKTsSVT5hcPAcIQVh5UMGBccIKbwnrLxgMPA5IYXHhJWboHKPkMJzRHV7BgDviSmcJ6zb+m/0C2AyYgrXmEPbElT+sRBAhrm0JUHl/ywAkGVObUdQMfGhFXNrK4K6OxMe2jLHtiGoAK2J6hYEdWcmOUCMoO5KTKEvc648Qd2RiQ1jmHulCSpAT6JalqDuxmQGaEJQAXqzsS1JUHdiEgM0I6gAI9jgliOouzB5AZoSVAAIENQdOJ3CnMzNUgQVAAIEtTo7YJibOVqGoAJAgKBWZucLazBXSxBUAAgQVAAIENSq3EKCtZizyxNUAAgQVAAIENSK3DoC6E5QAWZhM7w0QQWAAEEFgABBBYAAQa3GMxhYmzm8LEEFgABBBYAAQQWAAEEFgABBrcSXGQCGEVSA2dgcL0lQASBAUAEgQFABIEBQASBAUAEgQFABIEBQASBAUKvwc2sAQwkqwIxskpcjqAAQIKgAECCoABAgqAAQIKgAECCoABAgqAAQIKgAECCoABAgqAAQIKgAECCoABAgqAAQIKgAECCoABAgqAAQIKgAECCoABAgqAAQIKgAECCoABAgqAAQIKgAECCoABAgqAAQIKgAECCoABAgqAAQIKgAECCoABAgqAAQIKgV/Pzxa/RLANidoALMymZ5KYIKAAGCCgABggoAAYIKAAGCCgABgro63wKE2szxZQgqAAQIKgAECCoABAjqyjxbgT2Y60sQVAAIEFQACBDUVbkFBHsx56cnqAAQIKgAECCoK3LrB/Zk7k9NUAEgQFBXY4cKe7MGTEtQASBAUAEgQFABVuO275QEdSUmEcC0BBUAAgQVYEXuWE1HUFdh8gBMTVDp49v3L7dv37+Mfhlwu92MR5oQVIBVuXM1FUFdQaVJ41QAFCWowF5s6mhEUGnPAsasjE2CBJX+LGKMUnHsVXoktDhBnZ3JArAEQaWtiicCajFGCRFUxrCI0VvlMedO1hQEFQACBHVmq+86H50IKp8YmIuxSAeCCgABgspYTgaQsfodrQIEdVarTw6hZBZHx6Ixy0WCCgABgsp4Tga0YmzRkaCSZxFjVcYuFwgqQBWrf/dicYI6ox0nhZMBszAWOUlQybIYMQtjkc4EFQACBJV5OFEwC2OREwR1Njs+PwUoQFDJsatnFjuPRZvyYQQV4CM7R5lTBJWM1OJjEQMWJagA99jg8QRBnYlnH3CdCFpLBhFUrrOAAQgqExJoZmI8cpCgco3FBuB2uwnqPDzzgOtabfBsHDlAUAEqsknvTlA5r+Wu3YkAWIygAhxhk8cDgso5FheAVwR1Bp51wHU2eQwmqABV2ax3Jag8z0mAXRn7fEJQmZfFC1iIoPIckWN35gB3COponnEAlCCoAJXZtHcjqBznVhez6j02zQU+IKgAECCoHGNHDq+ZE7whqCN5tgH0YK3pQlABIEBQR1lpx+jWFnzM3OAFQQXYwUqb+EUJ6ggrDWw7cPjcSnNkpbVnQYLamwENjGQNakZQASBAUHtabWe40q0sGGm1ubLaWrQIQe3FAAZmYk2KE1Q+ttqOG0YzZ7YnqD3YCQIzsjZFCWprBizAFgSV99y6gnNWnDs2/TGCCrA7UY0Q1JYMUujDXGMCgsprK96ygpmsOodsSi4T1FYMToCtCGoLq8Z01Z01kLHq2jUJQQVIW3lzKqqnCWqawQiwJUFlXjYnMIa5d4qgJq08CFe+RQUzMqe2I6gAvLfyAWEQQU0x+GAsc5DBBDVh9Yns1hS0sfrcWn1t60xQASBAUK+ygwMqs8YdJqgAECCoV9i5tePaUsXqz1FvN/PxIEHdXYXJDjABQT3Ljg2AFwQVqMNGtx3X9iFBBWjNo5UtCOoZdmrAjqx9nxLUndk1A8QI6rPs0NpzjWFe5uddggrQgztC5QnqM+zMAKyFdwjqruyWqcpizyCCCtCLjWxpgnqUXS/AP9bEdwR1R3bJAHGCeoSdWD+uNdVV2tCar68I6m4qTWaAiQgqQG82tiUJ6iNuacB6zNt+XOu/BHUndsUAzQgqwAg2uOUI6mcq3coweYFWKq2VFwgqAAQIKvOwywUWJqj3VFrc3e6FOVWam5XWzJMEFQACBLW6SjtgqMgcLUNQP+LWBQBPEtTK7HxhDVXm6uaHEUEFgABBBZhBlVPqxgT1rSq3LExOYIQqa+gJggowCxvhpQlqRSYlQHeCWo2YwtrM4WUJKlDTxs/yhtv02gvqS6sPgpV3tqtfe0haeS5vTFABIEBQq1h5R+t0Sisrj62V5/SmBBWAvJU3MycJ6h8rf/gr72RXvu6sYeUxtvLc3pCgrs6Eg9rM8WUIKgAECOrKVt+5rnwrjrWsPtZWneurX/cnCSoABAjq7bbmLmrVHSuMsuI8f8mcn56grqjCxFp9cYMRKsz9wgQVAAIEdTUVdqhOp4xSYeyttgZUuOYHCepGHzYA7QjqSlbbmQJtWAumJKjAXqrclRLV6QjqKqpMniqLGXDcJvNeUFdQJaZAlrVhKnsHdZNd0zRcb2ZRaSyK6jT2DuoKTBbgEevEFAR1ZiYJUEWluwJ37BvUDT5cYCM24MPtG9TZVZscNjDMxpgkTFABqqi2EV+MoM7IpAAqKn5XYM+gzvyhiin0M/NacJY1ZJg9g0pfFRctgDcEdSZ2lkCCtWSI/YLqtAQwTuE1eL+gzsqOEkiypnQnqDOoPPAL70YpovIYrby2TGivoFaeOACrKLoW7xXUGdlBAi1ZY7oRVAAI2CeoM95iqL5znPGaw0eqj9UZ15qC13yfoAJAQ4I6yow7RqAua05zewR1tlsLBjYwwmxrz2xr80V7BHUmsw1oYC/WoGbqB7XYDmgZrjurMWbHKHTd6wd1JnaGwAysRU0IKgAE1A7qTLcS7AiBmcy0Js20Vl9QO6izmGngAvxhbYoSVAAIqBvUWW4h7LgDnOXaw7N2HLuzrFEFrn3doAJARzWDOstOZ5adH8BnZlmrZlm7T6oZVADoTFBbmWXHB3CENeuyekFd/JYBwDAzRHXhNbxeUGcww6AEzll4QWcsQQXgHweC02oFdYadpcEIcM0Ma/kJtYI6mpguOxGAF6xlp9QJqoUcIGd0VBdc0+sEdbTRgw+AoWoEdfRORkyBikavbaPX9ifVCCoADCaoV43ewQF5i52MmrLGHbZ+UA18gLoWWuPXD+pIdm7ADqx1h6wd1JE7FwMM2MnINW+RU+raQWUuiwx6gBYE9QynU2BH1r5PrRtUpyGAfSyw5q8b1FHs0ICdeZZ615pBHXVRxRSAO9YMKkBrk5+GhnJK/dB6QXU6BRhPVN9ZK6iTXkQAOpuwB+sE1V/iADCX0WvjZFFdI6iTXTQAeGvuoP788Wt4TEfvwABmNnqNnKETv80b1EkuEAf5vGBfo6N6u02xBn0d/QLemeCi/DXDIAHgmD/9GLR2zxGMmSL6h5g+Z8bPEK6yDjxnxnWg42c47oQ644UHoJaXrWkc1/7PUCd6gAxA0Own+sb96RvUVUI6+6AA4LxGYe0TVKdSAGYT7lL7oAopsCrr1/NWu8MXPPC1DeqKg3G1wQDAdYFetQmqW7wArOZit/JBFVIAVnWhYdmgiikAqzvZslxQxRSA263Gd1FONC0TVDEFoJon2zbvvzYzQoVdFQBDXA+q0ykAVT3RuGtBFVNuN+MAqO3gGnc+qBZRAHZxoHnngiqmAPCKLyUBwBEPDpPPB9XpFIBdfdLA54IqpgDs7k4LjwdVTAHg/z5o4rGgiikAvPamjY+DKqYA8LEXjfw8qGIK7M46yCO/x4gfmwGAq37++HU/qHZlAJy14T828nFQr8T02/cvO15IABZ3sV/vg3o1pgCwoj/9O9myrx/+z54lpABU8qdrp/75tt1jWuV9AJDzRBv+H9R0TH2hCYAqDkb166n4Oc0BsJMDt4Cf/zlUMQXgiIq9+OQ9PRfUihcHAJ5xp4XHg1o5ppXfGwDHHX0M+kE3/nsYk2d/0NUXkgDYwZs+/vf3P977xQBw1g4d+f0ev779DwDAk759/+Jfm7GRACAgG1TPTwFY3cmWOaEC0NYmdwK/Pv4lhW3yIbO4R+PUnSHI+/nj17ONyJ1QTWoYw8aQFWwwTt3yhZltsAhBFZmgrng6tVAB8Jkn2+aECkAfxQ8y14PqdApAVU80zgkVAAKuBXXF0ykAPONg6/Y7obrdCzBO4TV4v6ACQAPng+p2LwC7ONA8J1QA+ip62/dcUFc9nRb9EAHo4EH72p5Qv33/0jxiPf4MAPrrtb6H/pzng3r0dCpyACT06smRP+eTBrY5oc705s/8WgDaKrgmPxfUI6fTKxfJ7VsAPnK0DVc7cuGU2v5bvq1uEQsvAPcMOKAdD2rL02mPLy7BajzSoLpZDlJv+3bylDr+51AtBAB85MyPaJ6J40dO/L5jQT17Ok1cjCN/1qo/FwtAGWNPqE6nADzjTDfOftHo0e9783syQR15Ok3/egD6abFGD7pr+TiorV6Y0AFwRqtT6pnf96KR10+owghABRcPkJ8H9dH//F5Mz/y+1n9pBMAZ1p01nXkmes/BU+r4H5u56rMQmwgA8/tsrb63xk+4vp8P6tnTafrPA4CUswH/+ePX/aD2DKOfIwXgWU/+WMuh33PBuRPqCqfFFV4j3NPzW4wwgxXG74PX+HFQz54Yz36J6ZEVLjQA8wn8hQ1HPX9CTcfN7V4Azup94Prkz8t9y9fpFIAWWhy8GpxS3we154+hXL1IC32dGoAHev3zbFfdeZ1z/xyqMK7B5wSM1OGvFTzidVDPnk5b3e4FgBl90LVxJ1RfRgKglw6PCP8FdbbTqS8xAexntrX/iTaOOaE6nUIbNpRUlehG41Pq46CudDoFYF+DT6lzf8v3WUJMBcYxuxsxB678mb9/7+dBbXE69Y1gAJ51tA2N/lrBI7/v6+EXMaMVXzOwDmvMOKNOqWeD++37lza3fA1CAGbV6Iux54I6279GAwB/DPorDPMnVFEEYFUXGvZ8UFv9DKkQA5Ay4MtJ2RPqlW8FszYbIqCKk+tZrZ9DBWxuYJDngtrq30q1AACQ1vnLSf1OqKIJwCpONGv8LV+hBaCVe4050p4n+/T18S85IPVXQgFAWqf2nPtD/tw/Fkhe8k3u61JzymdxnfWNlw5079wJ1UADYCcHujf+GSoAFCCoABAgqOR4FDAPnwV0J6gAECCoABAgqAAQIKgwC889YWmCCvCWzQ0nCCoABAgqAAQIKlTltiV0JahkWcSBTQkqAAQIKgAECCrMwK3yefgsOElQASBAUAEgQFABIEBQASBAUKEyX7CBbgSVPIs4sCFBBfjDZpALBBVGs4hDCYIKAAGCCgABggoAAYJKG54LshpjlosEFaoTCuhCUAEgQFABIEBQYSS3Y6EMQaUdsQA2IqgANn8ECCoABAgqAAQIKgAECCpteTY1B58DNCeowN5sNggRVBjFQg6lCCoABAgqAAQIKu25tcmsjE2CBBUAAgQVAAIEFQACBJU+PKsCihNUGMEGYzyfAWGCCrsQEGhKUAEgQFDpxwkJKExQgf3Y3NGAoAJAgKACQICgAkCAoNKXZ1euwWiuP40IKuxETKAZQQWAAEEFgABBpT+3HRnF2KMhQYXefv74NfolAHmCCgABgsoYbr3RmzFHY4IKO3G7GZoRVAAIEFQACBBUxvFMCyhEUIH6bN7oQFABIEBQASBAUAEgQFAZy7MtWjPG6ERQASBAUAEgQFABIEBQASBAUBnPl0b62e1a7/Z+GUpQASBAUAEgQFABIEBQoTfP9aAkQWUOIgMsTlABIEBQgZrc9aAzQQWAAEEFgABBBYAAQQWAAEEFgABBZR6+lQksTFABIEBQASBAUAEgQFChpxmeE8/wGqAgQQWAAEEFgABBBYAAQQWAAEEF6vHFKwYQVAAIEFToZaZT00yvBYoQVAAIEFSgnp8/fo1+CexHUAEgQFBhV56jQpSgQg/iBeUJKgAECCoABAgqtDbz7d6ZXxssRlABIEBQASBAUJmHH8Yfw21fiBBUaEmsYBuCCgABggo4SUOAoEIrIjWWZ/J0JqgAECCozMFpAlicoEILK97uXfE1w0QEFQACBBWoy6MEOhJUxqu26K1863Tl1w6DCSoABAgqAAQIKgAECCpjeX46nwrv4aVqY4xpCSoABAgqAAQIKgAECCpQn+eodCCojFNtkav0ZZ5K7wU6EVQACBBUAAgQVAAIEFQACBBUxqj2haSKqn0xyZijMUGFhGrxAZ4mqAAQIKgAECCoABAgqPTnyyGMYuzRkKACQICgAkCAoAJAgKACQICgAkCAoAJAgKDSlx9bYDRjkEYEFQACBBUAAgQVAAIEFQACBBUAAgQVAAIEFQACBBUSKv5sY8X3BA0JKrAfmwUaEFT6sYgBhQkqAAQIKgAECCoABAgqAAQIKgAECCqk+BYzbE1QgfdsDuBpggoAAYIKAAGCCgABggoAAYIKAAGCCgABggoAAYIKAAGCCgABggoAAYIKAAGCCgABggoAAYIKAAGCCkn+2TPYlqACQICg0s+3719GvwSAVgQV2I/NHQ0IKvCa58BwiqACQICgAkCAoAJAgKACr/nCDpwiqAAQIKgAECCo9OV2IqMZgzQiqJBksYZtCSoABAgqAAQIKgAECCoABAgq/fniDqMYezQkqAAQIKgAECCoABAgqAAQIKiM4csh9GbM0ZigAkCAoAJAgKACQICgAkCAoDKOL4nQi7FGB4IKAAGCCrznRAdPE1RIESHYmqACQICgMpZTHVCEoAK12bTRiaACQICgAkCAoAJAgKAynmdcQAGCCtRls0ZHggoJFRfuiu8JGhJUAAgQVAAIEFTm4PYisDhBBWqySaMzQQWAAEEFgABBBe5z2xQOE1TmYfEGFiaocJWNAHATVACIEFSgHncNGEBQASBAUJmLkwWwKEEFPmeTA4cIKgAECCpQixM1gwgqAAQIKvNxwgAWJKhwhfgDvwkqUIcNDgMJKgAECCpzctKYi88DHhJUAAgQVAAIEFSgBrelGUxQASBAUJmXEwewEEGFswQfeEFQASBAUIH1uVvABAQVAAIEFQACBJW5uZUHLEJQgWNm3dzM+rrYjqACQICgAkCAoAJAgKACQICgMj9fOuEeY4OJCCoABAgqAAQIKgAECCpr8KyMt4wJJiOoABAgqAAQIKhwhtuNwBuCCgABgso6nAr5w1hgQoIKAAGCCgABggoAAYLKWjw7wxhgUoIKAAGCCgABggoAAYIKZ/z88Wv0SwDmIqisx5dS9uWzZ2KCCgABggoAAYIKrMHtXiYnqKzJ4gpMRlABIEBQASBAUAEgQFBZl+eo+/BZswBBBYAAQQWO8dctwqcEFQACBJW1ebZWn8+YRQgqAAQIKpzlmSLwgqACQICgsj7P2IAJCCowL5slFiKowGOeF8NDggoAAYIKVzi5Ab8JKgAECCrwOadwOERQqcG3QevxmbIYQYWrnOCAm6ACn7FZgMMEFQACBBUAAgQVEireGq34nqAhQQWAAEEFgABBhZRKt0grvRfoRFABIEBQASBAUCHJrVLYlqACr9kUwCmCCgABggoAAYIKAAGCCmkrP4Nc+bXDYIIKAAGCCgABggoAAYIKAAGCCgABggpp375/Gf0STlv5tcNgggoAAYIKAAGCCgABggoAAYIKvOaLSXCKoFLDLH8HrRjlzPKZwkGCCgABggoAAYIKAAGCCszLc1QWIqisz6ILTEBQASBAUIG5uQPBIgSVtVlsgUkIKusS0334rFmAoAJAgKACa3BKZXKCyppmXVxnfV1Ac4LKekSrrZmv78yvje0JKgAECCprcULBGGBSggppFvz2XGMmJKiswyLanmsMpwkqa7DQ85YxwWQElfmtuHCu+JpX5DozEUEF/k+c4BJBZW4WeR4xRpiEoEIrFvp+XGsmIKjMyyLZT4VrXeE9sDRBZU4WR84wbhhIUJmPRRFYkKAyFzHlKmOIQQSVeVgISTGWGEBQmUPFBfDb9y+jX8JhK73WoyqOKaYmqIxXceFbMVArvuZHKo4tpiWojGXBm4uowmn1Jg/rqLjQVQmSzwae5oQKKZUW7ErvBToxaRij0gmoenx8VnCIwUV/Fug1VfncdvrM6MotX/qqsijfbvstzFXeb6UxyFQElX4qLWRV4vKsKu+70lhkGoIKz6oSFSBKUOnDiaCOKhsKY5IwQaU9CxezMjYJElQACBBU2nICYHbGKCGCCgABgko7FXf+Vb6Qw2sVxyrdCSoABAgq8DwndXhHUAEgQFBpp9opptr74R+fLQGCSltVFqoq7yOpyjWp8j4YTlBpz4LFrIxNggSVPlZeuFZ+7a2tfG1Wfu1MyYCiv5V+5s+ie4zPFASVwWZeiC28z/FZsjmDjHnMsiBbfK/xObIpA4659VicLbxt+QzZxP8AuMxayPXPED4AAAAASUVORK5CYII="

ICON_B64 = {
    "IMC_0": "iVBORw0KGgoAAAANSUhEUgAAACAAAAAiCAYAAAA+stv/AAADWElEQVR42r2XS08qWRSFv30KqtpCL2BUULSRTrwDHd6O/4E48fc6cGjiiDgwJiQmEImmuUIpb+q1e1Al/RhdDVCzU4Nz1l577bXOEVXlq9/d3Z02Gg0KhQKXl5fylT3MVw8fj8d6e3vL29sbrVaLRqOhawUwHA6Zz/10JXQ6HdYKYGNjA9vOJscLlEql9QLI5/NydHREHMcAnJ+fr1cDzWZT2+02IoKqcnV1pcPh8NM6kM9OwfX1tTabTWaz2aL/pHtYGYudnR3q9TqFQkGWzsDj46Pe398zm8+TxouAgBhBjBBFMX91u9zc3KymBcPhMCk2rfijxAWHkixeX19/ec/MZwD4vg+qhGGEMYKIIYoiRARjDHEUIcYkDK2Cgel0SoxijEEVYo1JNKSoJv+NMcxnMzzP06UDiOMYFIrbRayMhTEWmUwGY1mICPlCnkwmIXX+iyx8CkC73UZV+fPHj7T/mogQQUSoVqsUCnmiOObp6Wn5AN7fB4hALpdLqRc01oUZBUHA5uYWIkKr1WIlLbBtG8dxSOoGkaR6gPlsxvfvJ6DKeDxePgBjhFqtRr/f/0eAwsINuz9/cnp6KrlcjjAMlwtgMBioZWWo1Wr0ej0skwhPUjWICJPplNFopNVqlSiKlusDURQRxxHdbpder/c/Q08NKVY6nQ6j0YgwjJbLwGQyQcQwGAzwPI+PDDGWQcQsmOj3+wR+sNDF0gBUKhU5ONinVCoRBEFStYBlDP8+KgxDan/UqFZ/X74I6/U61WoVY8wiACwr8588yGaznJ2dcXFxsfw0dF1X9vb2xLbtRfP398tYllnY8bdv33BdV1aSBR9fqVSCdPROTk5wXRdBMJbh8PBw9Teig4MDUMWIsL29zdbWFqrKb45DPp+XlQOwbRtNU9G2bQ4rlUUkr+VOmIykIALGGNw0G/wgWA8Az/PSkYuYz+e8vLwkYeT7vL+/68oBWJa1eA+o6sKU9OPOsGoA5XI5DSeD4zhUKhVEEg8oFourF+Hx8TFGBMdxcByHcrmMiFAsFNajAdd1Jbe5STabxXVdsdIr2e7u7vpeRjnXxQ8CJpOJfmggm82uD8BgMMD3fcIwTIUIz8/P6wHw8PCg0+mUTEq9MQbLMnieR6vV+tQY/g3Xt3WvS12z9wAAAABJRU5ErkJggg==",
    "IMC_1": "iVBORw0KGgoAAAANSUhEUgAAACAAAAAiCAYAAAA+stv/AAADbklEQVR42r2XzUvjahSHn5OmTW36bVpaahGchbpSiiD4p89wB9zOFe7gQu9srDAyxepYMW1MkybnLtJWZ+5mKrEvCSSEvOfJ+fxFVJW3LM/z9PT0FM/zODo6Ynt7W96yj8Eb19nZGf9++8b37zf89fkznufpWgEGgwGGJK9PxmOen59ZK0ChUFheZzIZDMNYL0Cv1wMSr3e7XWq12npzoN/vo6qoKsPhkOFw+KYckFWqoN/v6z9fv3J7e8vU90GSjxYRBCgWi+zt7XFycvLH3jBXof346RP+sw8oIgJIEobkwHVdvnz5G9u29eDgQFINged5GkyDheP41W+6zAdFGQwG6eeA7/tEUUQcx78ZfllxHCMIT09PpB6CHz9+JCZVCcOQTMaY50AShjiOUSBjwGg0St8DQRCgquTzFtlsFhFjbjwJiWmaOJubCMJsNksf4Pr6GhFha2sL27b5vXZUYXd3F9PMMJtFDAYDTQ3g4eFBB4MBIkKtViObNZffrq9QbNsml7MA5fz8PD0PuK5LHCeG6vU6vu8v84F5H1FVxuMxjYazgE4PYBFTx9mk3W4ThrOXBjQfSCLC/f09vV4PwzAIgiB9gOPjYyaTCbPo/0mmmtS/4zg4jkMURWkCRGQyGYrFIjc3N4vEfznn974/JQgCLMsiCALG47GmAjCZTJjNZlxdXfHz58Mrq2CIsRgJqCqu6zIajYiiCNd10/FAqVSkXC5RLpdRjX95ls9b6Cug6XRKt9ulVCph23Y6nXB/f18sK6c7Ox/k7u5uOX1EQMRYjCQUxbZtDg8PiaKIcrksqTWinZ0PAtDpdF5muQiOs7mMiGEYbGxs0Gw2pd1upzsNF6vRaJAxMnMpZtLpdBL7CnnLolqtrqSMVgao1WqS38gDkM2aVCqVpB8YQqPRWI8ky5omIkIul6NSqSwFqWVZ7w/geZ5O58KkWCzSarXEsixUlYnnvT9AEATzNqt4nsdoNNIwDAF4fHx8f4BExCqqEEUxYRguVVIYhiv/Ia0MYJomhpF0v2LRptlsimVZCIJdKFAoFN63CkqlklQqFVSVVqsFQLVaRVVpNpvrqYJ2uw0i1Ov1+Zh2EJH1ATQajXkYZFl+IlAul9cDYJomGiu3t7cASxn+J9MvFYDLy0sUxZt4S8ESq3JxcbHyXv8B28J/Cs17DQIAAAAASUVORK5CYII=",
    "IMC_2": "iVBORw0KGgoAAAANSUhEUgAAACYAAAAiCAYAAAAzrKu4AAADeklEQVR42s2Y204qSRSGv1Ut0M0ZwcSwAU32hRrjxeiFj7Dnykf0WXwFt2bPqDfqjRpPyLGh6VpzATQyJpMZEJxKOp0qDvVl1Vr/v7pFVZlnHB8fa6vVQoHff/xga2tL+IRh5vnx3d2ddjodVBVV5eLigs8ac4FFUIAgvL29/T/Avn//Lp6XRBBUlcPDw08DW5n7D1YcQhuCguM4nwYmsyT/6+urXl5e8uvXHzQao+MTwRhDtVJhZ2dn7iL4z2AnJyd6+vMnahV5t7UynBgBq0rS8zg6OmJ9fV2WkmPn5+egICLAZM/xTHVYCF3fH353Gcn/9PSkg8GAjzGeDooCqsrz8/NywG5ublAFtXYYmghx+m5HxVCv15cD9vj4iDFDaej3+9jQDkGVkcjCIBwQhhYFer3+csD6/T6IEI/HicXjiGMmyTW6HGeFTDqFMQZrLY1GQxcK1m639f7+HlUln89hHPMP2raCMQICp6eni43Yy8sLXd9HEIIg4IPMvJv6fg/HOIgI19fXiwXr9XrR5iIyBTY28fGwqmQyaUDw/d4SvFIglUpRKpWQKQ2Toa7pJHTb29uIwKxt1b8GM8bgGMP+/m80m63o+NRqFDFVBQVrLa7rks/lsGpptVq6MLAwDBGEYrFIu92KNDUyAJHJHXh4eCCfzxMOwmEaLKq7aDabhGHIxZ8XUb7J2Cx1Qjg+4PrbG81GA2ME3/cXd5SxWAzP80i4Cez7xAcSbuJDy9PzfcrlMqlUCs/zFhexvb09CYJAy+UyZ2dnUwqx4jigig3DaM1xHA4ODuj1eqyursrCwAD29/cFIBaPa9jtTsnF2IbGI51OUyqVZu7JZmqt10qlqXmxWMR57wSq1Gq15ff8u7u7Uw3PxsYGuVwuWnMcQ7VaXT5YuVwmFotFFVitVqnVahgZVmUmk6FQKMjSwSIbAhKJBMlkks3NTXSUZWEYfs3jW6fTiQQ3CILI1GVUqZ1Ol3q9rksHa7fbIw8cxigIArrdLmN5U7UEQbD8iGUymWGHMdJ6x3FIpVKImfjUvM+Ys8nF2pq4rjdyhBVc1yWZTBKLxQBIet5MovopyV+pfEOAbDZLOp2WQqEgrusCyrdK5eveXWxsbCAi5PP5aC2XzSJAbU4Nmwssm81GsvF3CRl/9iVgt7e3WGtpt9vven0ftcrV1dXcYH8BUkiZJmisGmoAAAAASUVORK5CYII=",
    "IMC_3": "iVBORw0KGgoAAAANSUhEUgAAACYAAAAiCAYAAAAzrKu4AAADjUlEQVR42s2Y204iWRSGv1WHcGokoLQOGowmQmwz3njhzfgQvkLPy/kQXnqrZtroxbQmokmrCSIqoAh7r7koqOZgMjOOhbMrlRQ7VamPf63977VKVJV/O6rVqu7s7NDtGgC2tn5jY2NDeMfhvOWharWKMQYERODP79957/EmMGstCvQlMt3u/wOsUCjge34PUllfX/94sGq1qvv7+3S6HYyxgHJ4eMjp6am+J5j80+Q/ODjQo6MjHh8fMcb0QtkPpiIixONx8vk8W1tbzMzMSORgx8cnuru7OzDTf0ZG5gRFSafT/P71q0Qeym/f/hiA6QO9/l5BeHx44Pr6WiMFazQa+vDwMDKrI6Cj6gmXl5fRJn+9Xqf98hLgjIVdR0AVay2IcH5+Hi1Yu91GRLBGabfbYeIH50+VVJVOp4sxBgEazWa0YFdXV1hrcT2XRCKB4zivBlVE8H2fRCIOIjy1WtTrdY0M7PjkBFVwHAcZy/mfuRbAgYiDAN1ul0qlEo1iNzc3+vz0DCiu647lmIxcq4KxBun9g4uLi2jAnp6esKoIgu972BEwVQ1hA+0UVEkkEqgqjUYjGrBYLIYjAVQ2mxtzCBFBxBlwtkDD9fVfESGoQKIA830fx3EoFos0m41AHR0MoYRACqhajLXEYjFSqRQvPZt5y/D+xlxRlK4xtFqt3orUQDgNrwYkdHAEarUaxtjoFGs0GriOiwCdsOaS4JBXTsAq3N3dBbaBRgO2vLxMofAL5XIZ1xm/1fO8AV/THrbi+z6lUolyuRxNKJPJpGxvbwOwt7ennc5wpdqHstYOGUc6nWZzczP66gIgk8m8ukfqEFSwPKenpydXwRaLxUG3QlGSyWTobf05x3GYn5+fHNjKygqe6w1VY6urq8TjsWAr6vna7OfP5HI5mRhYLpeTRDIxtBEtLi5SKBQIRBNQZWlpabLNSKvV0ufn56HE9zxvIJ+CkN7e3k4W7P7+HtM1YY5ZDeqzWq021gxPFCwWiyEDXqaq0OuMwlUqMlavTSTHPn1Khb9dxyURj/dySkIDmV9YmHzDu7a2hmrQQ2YyU2SzWZmdnSUei4Urde3Ll8mDlUolXNdDVVnoKZNKpaQwX0BEmJqa+s+N7pvAMpmMzMwEqzCfz4fz2WwWBebm5j7u24W1FjTonvqj2WwGFUin8zFgZ2dnWq1WQYYhWq0WxlgqlQpXVz/e5ePKX2udkdsHtQhGAAAAAElFTkSuQmCC",
    "FAT_0": "iVBORw0KGgoAAAANSUhEUgAAACAAAAAqCAYAAADS4VmSAAAELElEQVR42r2YXY/bRBSGnzPj2HGSTTbptrttt2jVbYtahJCoqMRN/0AlJK4REn8NuOJnICrgAomLSkiFUkpB3e2mWZI4seOvOVx4t5VQRdVdryONYtme8eN3zjvnjFFV/q/dv39f33TPm9qDBw90Mpm8dhzDKX9ufqCn6e+d+MFprPz4Nbz4HdffVLnzGTLYkrcd5+QKzJ7B5DFSpMjsGfr84YmGOTlANEZcCQI4B/NxwwD9C6jnV8fWg+6oWQBzfld0uIM6Rb0ObH/QsAKAuBwtHWgJedwcgHvxRN33X6lM/sB4HpIt4advcE9/Vo1nemY2dONflUffwd5vkCUoCmKqIJz8CT98ifa30J331dy8J7UD6OxbZPoLUigYobIAIALYI3fso/kCd3hDzei61DoFkh5Savm6Ky9hCgGnBSxe1BsDLp0ryYIkSilLB2jVlJfHTpVoGkNaQHpYcxDGE9gqIWyxmMeUWYkWDo6SiitKsjQnjnPMQMDfrxnA5eCg1dkgvHAF1SrY1TlwerQeBQyuvofGBmyBJpHWB5BE6JMMf/M2rd3bGM9U6h9Pvwhep0f3o09gtgEHCyiWNSqweAgRyOAKnNtBrFfldHccB0B3iNm6Idh1iJ6jydN6AFw8VVoT8C1iLRQpoooxr1woAqxmuHiq0u5DUMLqr5oUyFPwSkTWoL0G8wOQV29+bATJEzj8G85fhVTQfFHXFCjkwPA6cm5HimiKAmItxrOICGIEdUqZpXDxFgTbSBzXBKAOxgqXq4xn44PqtUWqFdGY6l8dNoswQVfYvAPTvCaAMkeiHLwAly1VgkPkvwoBmBLKvaMaoQ2LJS6L9fQA2ZJltIB4WqXdTXnV0++CsZUX2wbtJ2gy1zJNWE3HkCU1KOD5RHRQ04IyB1/BrzTQ0TvQCkEVOgaxDpzD+X1ib4CKOT2AOX9NRh9/iq5vV+nXAu2jrq1OdQ6FNQNaxYWMLtO/+zm2O5Ra0nFw6V0BcKu5ogbtCDID/A5qW4gI9C1oiIQD8QHWRjWuhMcd2n2h6EPPVC4I1yFYAw+kbcENG6gJzTtV0HktpN2H3gZYRXOB1uUGAMJbsC9gAwgHsL4NK9DHAqPds9+aid9D6VKqYsMBqg6Xl1C0sUFXzl4Bq9AXpOVD0EGMhxiD6b79PvVEAEoONsVIAasFzPcwHjAqcLN9PXsFRKoiJIthMYblIVgBT6rK6eynwEfDsNoXuAI8HwIDhQedRmzYQwZD8Ax4YeWEQNDODUzQkzN3gWmvi2tdUtpjCDqgJeoZZHizwc2puQoaHOUBkGKItDYaBAhGkJWQzCGaoNIDEzQH4J4/QrMEVxZoWaDTPdz8oDmANF6SnruGWb8Im7us1rbJ5v8095Ws++E9celSJeiKBcK7X6hp9xr8SgZV8fnSGW//cIB/Afe7HnfLNG+fAAAAAElFTkSuQmCC",
    "FAT_1": "iVBORw0KGgoAAAANSUhEUgAAACEAAAAqCAYAAAA9IzKsAAAEa0lEQVR42r2YSW8cZRCGn/p6n9XjDNiWA05IFFkkIQcuEScEQuLMD+UHcCBnJxcORErAAcdEOHbs2adnppevOHSbcdgUPONpqQ69qPrpt96q/rpRVf4p9vf39fDwUP/t/P+Jvb29/8xjWGCzgzdq+8fKgpt7aYCn3ynPvgcBe+dzNfe+lsvmurwSB0+QbFLE7z+iozNdKYQddZQ0BgEQiDvobMxqlXAciNZAFVTRoI54wWohTNQUvfkQcosqsH0faWys3hPiuFhrUVUwzmq7w076yvHP8NMjjO8Xvjh4jA1qyvUHmKghVwahoxPVwz347RkMXyM2nxtz0oUfvoVf97Cbt5QbDzGNLVk+xOkjOHqM9HMQKeP8pCAo9F6hyStYG6PhNyp+RZbmCZvGymi/6IaLabUMSkUEMAbkCEanSzZmnkM/ZtydkOf2r3f/kyFJLfEoQc8GMBsuGSI+hpuKU3fpdYZY+/fhqArd3ogszZD2DOV4ycZMukjFgBvgVAyzaYrrOnieAyLkeU6aZKgTosaB0EPjzpIhphN0kOI3dwnqFeTlHiJyYYA6mNDw3vXbaNSE46eIFy+5HMMD9Jcc036AbNy+4M15h4iAqbZwdr8kf2HR00PstK9LgdDuK2XtBKmHSFgD475lBLWlSVXBCFSaOJUasjGEs+fLUULtANwEiMALi9YrS6GqZZMU+zIbI1kKlXZxKD1aVjkSOJmB2YZqGx2czIshUvIoiKDxALIZbHwCxwLZYEkQ0xSOLHz0GRLVJe+/mT/9+eREiookU9RmyOZdSLehO1kWRAJuC7NxR+xkoO70Tam+vj2vBEw2hnSKVFvC+i1klC4BQhVmI8jLZJMT2NT5058bUrXYj2bAcG7abIqNe7oYhM2Ydk6Ih2ViJ4YtF7xCCfUrqOsXUK6gOx44o4Ihz+medWDSW1AJMWR+ndRfKw9kSCAQlq+O5iZU1+eZWi5qk+LK6BqpVys6aqGJaRyq978gu/lpKXGA+gYqBhnkYHPwgsKXPhAYJCtSOtfvca29g2lsChzqQmPbiRriRI0SqgkWaBp4nRVliJrAIdQcxCrqVovE1aZQbV7BGjNah9iHmlNMR78K1XZhzMigiQGnfrULXeNVhOk2JOfd0IL1G6VdFOIG6BVDFDrfgpczsBaCClRbKAZOMxhdQ8LmCiBq70PFQ0VQNwLHRx0ffNCgxruuKxeDSDK0k5ElgBchToAGa+TdBMbJij5+pI/suLiRg9EM1RxDhtPykPUhGvf16iHIinmgOTruQDqBaQ9cB/wM8mQVxlwDLd8bszHY7MLEqb7ThFwYQvw2RG3UCHgh4oUQ1CF0gC0krF+9MaW+JYQ7UHEgrIEXQbUFUQDR7gq/yr2PoRIhblisOSs1yNuY1o6sDMK07wqjALUZqIUkBfPhan+c2binpCk67kE6RUc9xKuu9k9N8uIJaTxBwiri+mjUJDl6TnJ8oCtTQjZ3SUyE98EuEjVEd79S2z/Bq69fSok/AC0XPQPcTNc+AAAAAElFTkSuQmCC",
    "FAT_2": "iVBORw0KGgoAAAANSUhEUgAAACQAAAAqCAYAAADbCvnoAAAFAElEQVR42sWYbW8UVRTHf+fOzM7sc0u3D9AWWiBVFKKEGJW3BuOnMPG1H8vvQPQVLzUxwQhiFKQBpaXtbku73dmHmbn3+GIXuk2QCJ22m9xkNztz7u+e8z/nnntRVf5rNJtNvXv3rr7pmbcdd+7ceaM9nxw+buOh0t6AqQuYqQtyFFtHBnLrD5Qfv0OyBIpV3M1v1DSW3hnKHNk9L9aQrA846O3B3vMjmTsykL54NvwiAmKg9eR0geTsFfACQMAvwNzKKQM1ltGwijqHBmVkYv6UQ9Z8DGmMOgtJG916xIlnmevuKttPYe1XZPMPsAkSeOBSeHAbt/VIWfgIGhcx5Uk5ViDXuqf8/j1srnMwk4wGkPaQ5/dh/T46PYN++JXK9HU5lpC5eFPZvw2DDUTHYca5xn6nTbTzA66zocejoZ2fEW0jsY5xjM2lY4AC0gXRfdj+KX9R6yBWWEMzxQ7scPLXrVv11X924NBMwayjvbbm66HeHhS6kCpbOx2sc6+jGQIB1jlauzGkQNCH7m6+olaboq0EWbMMBhmtVptiVKBcjvD8g3VZq8TdHnG3T6IC/yTAAGbSfIFksA9bMa4BpUbIlFfEeIK81MwoIJ4nVCsRxShgK43ROYc878BEN2cN9Z/BdEK60adUKWBCDxEZalhfEuloWxP8osfkRAXdBmYStP805yxzG8ishwL+hQCm5HDKH0o1hfMBxaUKxhSQ+QDcOpp0NRcg7XcU20EFRAL8agjBKKMYeslZPZx0RYF6hGoBRRCNwdm8PKTgEngieHOf49ISbNpDdWiop7EKuZqRDgJc4xNYBU37qLocgXYH4M6jjQ+I7+2jiYIZr9Iy1hcpNs5o/7KNm1wGuQzbMeQFpFkGzQ7ULxNoh9oZh4RCllriTp9+LyVJMvq9lN2dmJ1WB2uUiWUhkDY0rkKzh6SDnNK+0yKJY/zMYrw25loIOxbvYUrRRAySlH4/RQTK1Qi/6MOVEGY8iFuoniPpZxSaq/l4yPb26PgTUJ0BN0ACD2kUkJLBGCGKCkQFn0q1SFDwkZKHTHiIL2B7SPkM+4UGNt7JB8jMrhBe/RKmlsAEY5uoeaWdwSAbKxGA05F5wcxclOjaLczi9XxC5pXqUr1yczhXp6JkgKcgw71LRPCDUaHUUSdgDGQOvCIAtfc/G6n+kebbwnpT4Irgg4ZjKysEB3WyoMM61RPwZ463p5aogXZrqHMHG5gIXn12FKZhyDRzaLeChLPHDFRpCNkKPLWw70ZVSmD5U1RGCogtrCbQWUTOvN0p9t1OHQs3SJ8rGDfUTLGGNJah0hi2RL6Q7kA6ff2tTb8TkKk0xPU9st0Mm1m0Mo+Up3D1RWySkewlqFNMrXFCx6Ckq+F5H9IQ/TuFqIyU6iLFqqonBEsFZDYC2zuh2w/NYM4DG2A2Fe1sou1Nle42JvJhNkRLAfyPrSKfkIU1wYbD1xXobEPSHfbdOiqKmUBYPsmj9NmDc5iMCoDxD9qPOMTUz8nJAVWuAj7qAeUzSFSD+hwYQUUgfO9kLxukfAnMApQU6vNIZUqYXECjAIIJZPLjEwYqTgr+DTAehJVRFa9BEIK9hNSX5USBAJhYgf0C2u8eNHJdAVk8pfuh5l+QZYhNhh5yDslS2Hp8OkCbf/7GRuwNr/UAppdJavNsPH7EYHtd38Xmka6Fz976+pBOpFSX8ItvOXcEm/8C/I+Mu+r4Gd0AAAAASUVORK5CYII=",
    "FAT_3": "iVBORw0KGgoAAAANSUhEUgAAACQAAAAqCAYAAADbCvnoAAAFZElEQVR42sWY3W/cxhXFf3eG5HK/d5XI+ljJiKIkcF2jgaPERtG3PLRA/9iiT+1rHwMEBQykdWE5SGoldizJkkVqtSSXnLl94DqruAVqe1f2AAMsl8OZM+eee+fOFVXlctvf39fNzU2W3R4+fMjt27fl/40LXv4jiiI6nY4sG5D3Xl9lXPAmk2uWKuMTCEJkuLVU8G8G6O9/Qp7uo1ET/fXv1ezeXRoo89rUH3+vcrgPZYZcnMDBPTQ713cGiPQI9RUYAWNgfIxOJ7w7QHEXTAAzTiTuIkH07gCZ0U2huwrqAUE3biDt4TvU0OkjJT/Doygenh+g6ZG+VS/TyXPl5AA9/g6efIPkKRLM9vLTfXRyho5uqQy2YPVDpNGWKwPkn+0rP/wFOThE8gxEQKg1JHWX5DEkj9FeG67vwtYfVHojWbrJ9PR7JfkzmCdQZJdezMC8aDJ7kByG36JHf70aDenZ19BM4HGFvqwSERBTdwREkNTBkxLif+OP/qVLBeSzU4UHMHGUSYVzfs6KyOxTuUSVUFVK/jiDwEN6b8kMFSfQmKCZJz3PqZznZ5pUwSt4X/eZGZ3zJJMCLCDH6ORMlyfqcQrflciJo6ocp8kFg26MwRA1AsxsK855yrLCKRyepAyHLXg4BXMOgwRagyUxVD4DVXwTQit02hFBYImbIca8cDPFWqERBaCeQbdJWTk4roAM9elyTKbFheqz+2CULC+wLej1Y6LQ/s9JxArtdoPhoIWNLZlU9fl2fH9JGjo/RtYy2Am5SHJ6vxuiQ1NrRy65OS+5f2RpbEWUZYXcCEEeoXmqizM0TSFycFQvIp0A3Gz1S7r+r7YC8U7EtCjxiQeTgJZLYEgqKCv0fAUdrkIB5C+YUVClzsXr3zM5wdQjRqgG2/BjPY+6YgmAtESPgfXfUoYfkY0LtDM7MmY2Mr/4UiECXTGcHpwTXPsMs/IFJA6m2RIAJWPkR0Wu7bLRV5IHKdOnOeXUzZl5eQ+hMj7LoPAM+1P02m/QHwwkJwvGIVfik0PywtHKUuxqwdroGvrNhOqwJDnLcKVDRTACiCEIDB0X0ezFdG8NID0FI1xMhfinB5idO4sERmU8KbDrNyGIQDymE6A3W0TjCY04RL2nLCqMNdgoqM+xjkF2IySwaDlG+h3G3R3CIiNciCET0tn7I66cIo0mej4Tc9vWBq5ARCiykrjdmClKwBrEmlpi3qLNAb1PvyRothY0mQhBf01+fnESKerBzxYWnZ/uRuaiDgSsQAXQxzTa0t76ZPkprLoNtFIkUGjOo6A1Mo+PChoCoaCpg3DrCnPq9/fgUVgvJHMHC/srIHYWIRWZOPSohKMhMrhxdYBMf1OI7qD/qCCdpxp2+xY+6M4Co8LEw75De3cXul6/0q2j7H3AeCIUVYmvHN7EyPan6PYernR478nzgkk6pXrv46u/BoWRpXu9hW1bVEDjLjIcEezugWkAQrga0dptEYZy9YCwFTISgp0mNgiwUkGWIL7AWI8JBTNqwCiC/PwtVD9sUPfA1AIqxmjyFLxD0HpfXsDaX6YmV8ZQ0ENNdz7aVzC9AHXzPN8AUwvt964ekOmsi+YbEAlEBmyExF3oraPGotZAx4LfxLQWu+e/8t1eOndhHKFtoNGB/gi6azDchq6Aj6Dz+dsrNpjhdSHaA69o2ESGIzGtvjDcriN08RHS/fDtVj9kbQ9hHa2qS7mBRZ5bpPvZQkWGNyvHqKJlhZQF/uywPkSmEygdFMupor0WoLN/fkVy+ARtryJxu2atv8FF7kjv/Y0yebZwnei1qrDNj+9w0V2HnRtIXNeyza++FG8HGtiAsP/+wib7DzaAVddL3RGaAAAAAElFTkSuQmCC",
    "MUSCLE_0": "iVBORw0KGgoAAAANSUhEUgAAABkAAAAWCAYAAAA1vze2AAAB3UlEQVR42t2V3UuTYRjGf89mzpO3cB+5ZbLMSqItiOpgkpC4cB1kehQzPNGj9Xf1QTFQxKM2UZQJgZkHGWugQgYxad++e6fPsz2dV2fvW1D3H3BfXNzX9buF1po/PS7+wnQ5tSi3tqZPmhZ3R+9hGIZw3Ml6JqONk1N0o4Fpms46Kezu6v3FBQYsi69XrnJzYoJgMCgcEfm0s6MPl5fxvd/icq3G4dAQ0dQzQqGQsH2TLwcHOv/mNX25HIP1Oqrdoerpxph5yoX+fmH78O9Wstr18hXDR0WElEghaCpJcWSER2Njwna61hcXdCCdple1octNu62wgGogwLXZWfsR/rC5qb3pND6PB7fhoV3RWFJRcblRyRmGIxFhq4yVclnXXzznXLWGrtdRx8c0NXyXiqNEgngyKWyX8ePGBuc/F5CAbFkoUaPc0RTj44ynUvYbb5qmtjJvEfKUllRIoHLWoJV8wuO5OeEIVvLb2/jzBaRUNHWH4o0IA/Pz3I/FhCPsKpVKuryS5aJb8M3n43R6mtGpKXq9XuEIIGvVqt5aXWXw1m32znRzaXKS69GosIMf8fM/yS4t6XBPD3ulMncexPH7/cIuQH+JcF84zH6jQexhwhGB3zr5Zz/j/yPyA09mx+JLjndBAAAAAElFTkSuQmCC",
    "MUSCLE_1": "iVBORw0KGgoAAAANSUhEUgAAABkAAAAbCAYAAACJISRoAAACpElEQVR42u2Wy09TURCHv3P7sAiURgRMKoj4Co0moBAfkRijSOwOYtxgNOjCf4M/QReasNMdrFgCITEaghgjQVEkoQt5VGjBgNpye9t77xnXykPSoomJsz/nOzO/85sZJSL86TD4C/FvQlZXVzfU37ubgGQyKW8HhqAoIE1Xr1BeXq52NZNkIiHjAwNEqsMYponrOLubydjwsKz29nKspoZYxuJo2zUqq6pUwRDTNOX9qzGW+vsp//CesJUjMTdHaXc3h+vqVMGavBkZkcXeXio+TnHIskBrslpIRCLcvHhRFST8Yjwu40+fcGB0lKPraQwB8XmxcjYZA8LR6KbndgyZnpyUxcePiCQS+LxedEkJuC5WJoPtOKxVVNJy5kz+PpmenJTkwwecSK9TFgrhKwoQCARAwNUa29W4zc3sr6hQeUG+rKzIQk8Pdak0e0MhVDCI3+tDa43juliOJl1SwpHr0fwd/7qvj9r4An4DnHQKQwuuzweGQVYZmFrztaGBxvPn1FZ3bKvJ/OyslD5/hjJNbNH4bBvLssC/hxQG67bNWmkpka6ubR+6LWTm5Sj7lpdxPB4sU2N7PGgNWb+fdDbLmm3juX2HU6dPq7whqZdjlFlZbI8H11C4QM5xMbWQVgaZ9nZu3O1Svyv5lpClz59lTyyG4ziI4yAi2CJkcjbpYBDV2Un03r0dff8tIbGJCYqXl3Ecm5yAKxpLGaQiEarv3+dCa6vaqce2hKwMDhJWkBWwgO/hgwTa27nc0fFT88sb8mJoSOqqa5DjK6wtxFm/HuXcrU6qa2tVPr1O/bpIvBsfF3f2E5VlIWY+TFHc2MDZS5dUIaNgQybJWIz6YJDYwjzhtmucqK9Xhc6bDY4/2dLC1LdvVDU17wpg03L9X4m2ix+JhCktLw1vMwAAAABJRU5ErkJggg==",
    "MUSCLE_2": "iVBORw0KGgoAAAANSUhEUgAAACgAAAAjCAYAAADmOUiuAAADuUlEQVR42u3Yz29UVRTA8e99897rvJm2A51WQ4u1pYQCDZBoMMSFJrgwk9CFBMPOxLBz5YIF/4jEX2GlCRujJBhiInFlIBTS8qNIlBaqDWU6LW2nb968ee/ee1yoa9tpOzaxZ3/P+eSee89NrhIRtnM4bPPYAe4A/3fAhcqCXP3mityduCvbEvjz9Z8Y6Bsiml/l9q0x2TbAMAzl6qVL8mpbDteBueczHDg4/K/r3K2G1Wo1uXfjBs8uX6b/yTTeK/1M7R/mxIcf0NnZqf4z4IvFRRm/fp3w2vd0TU0xaAxKYOXhA5yTJ+nt61NryeNuRStvXbtG47tveWn2D7q1xvd9HCdDGEW8yLgcOH58zfk2Ffj40SP55fPP6J+cxE8TMp6HCgKCbEC4skJqLXFXkcLu3a0HTty8KcufXuTwfAWlwGvPk1oh19mJjupYY0hTTeq6ZIOgtcD7d+5I9eIn7K/XsW0eOTdP1GiQbw9Aa4zWWGvRxiBBlkKhoNaae8Njpvz8ucx9+QWDxqKCgPbCLqwVfN/DVaCNQVlDvdHAAgS51r4kY19/xdDiIl4+T1AokGkLSB3I5gKstUiqMVYwgHUUqqendcAH4+Py8u0xsk4GW6vhBzlqCPnePhCI4xQvkyGqxxgng1aK3L59rQNOXbnCrmqVeLWKL5ZwZgZHICOQOC5OkCV1MsS+T2wtse/Te/Toumo0fUmezc5K4f49JEkQ1yWJIuI0odDmE9dC6lrT5nqUV1dJlSLWmrC/n6GRkdYAnz58SK4yT91ackHAUrREe3ueamWeWpwQ5HIsJwk1EaorK8SOQ+HUKbq6ulRLgOWJCfYmKbG1WGMRERxHEcYNECGMIuqOQ72RkFjD6pEjjJ4+ve46TQPTqcfESYKnFKuNhHy2jcXlKubveZcCDWvRShEODPDG+fMUi0XVEuDy8rK45TKp/muEoBTVsEZiDNpaEmuxKLTvER06xGsXLnD42DHVTK2mgEsLCzC/gDWWRqoREVJrMAJaBO046J4ibqnEu+fO0bt3r2q2U00Bn00/IR/VMFpjjKEhgkFIlUOyZw/e22/x+tmzjDS5axsGzj6YZM/BwzQeTWKiOnUU9cEBiqOjvFkqMTg0tGHYP6HW+/Vxd3xCqnNLdDgO1R9/YObXSbreP8OJUolid/emwZrawUqlIk9/+539wyPEUY3yyEHe+fijDZ2xTQVms1nEc1ioLFKem6Z05j06Ojq2DNdUiwHGbo3J4L5BuregpZsC3Pn62AFuYvwJjB/NeX6uwDoAAAAASUVORK5CYII=",
    "VISC_0": "iVBORw0KGgoAAAANSUhEUgAAABUAAAAPCAYAAAALWoRrAAABrklEQVR42s2Tz2oTURSHvzv/azKt7UxsmiaitYq0FFoIFnyBLn0EwXcRce8TuHYl+ASiIIigUIltqU0TQ9qmhNhk6vy597oYt6YpWPCszuLw8R3O7witNf+6DK6grEmGDg+/66PuHjfml4iiM0qlRcKwJP42Ly5av9U60P0fz1le2CGSAZahOO07nCaPebC5JS5l2m43db/1lNLsMat3BaaUXDMHoBKuewmD/Td0u2u6XK6IiUzfv3utbf2WjaWPWOIcDA8sB2QMwgPbI4kyGs0Ki/eeEQShGGu6u7OtV2svmXG7YE2BdEEYoNIcalogYxzxk5vzguH5CAjHXz+TKa4xAJWBVoDOewxwpkHoHOzOUPAi2rsv6J0c67HQavUOn/bqKLMAhvMHKEDFuW0WQZaBYWEbMev3Dzjpdcab+r4virOPSNR0DhAWuCGYU2C6YPtABjIh0gEfvj6kVlu+OPwLlds0O3NomYJK0XIE6RCVKiIVgMzQ6Yhv+zXW608oFotiopw2Gl90r/MK24z4lVWZK2zTH97C9evEo8+AIixvsbKyIS4d/v/m968E+hv7ebXHyHxSVgAAAABJRU5ErkJggg==",
    "VISC_1": "iVBORw0KGgoAAAANSUhEUgAAACYAAAAZCAYAAABdEVzWAAAC20lEQVR42u2Wy24URxSGv6runounpz1je7BjT4wSRUJhIIBAkbkoF0tZJcusIl4FiVUegjcg7LJDibJgBQiIudgYiK0M8thKjD0zTre7e/pyWJQj9ngcEeRaVZeqjz795z/nlBIR3sWleUfXIdh7A2bvN8DdOzcli24xSKepeJ8SBG0sXeGjj+eYac6qt42r9lOVT5cWZFT/yHRtjYwSiR7DsWzy6BUb3SOs//MDc+e/U/+JYr1eVx4++Aklm0w2OnzQ9CHOsQix9DYkAyydMjseECc32Nn5QjzPUwcOtvj4Ny4cu45jRaBLoBtQyAALbBt0AmkASjM+NuDxo185cXJeRkdr6kBSufjkvrz66xZTjeccm3wCeQIo0AUoVCAbQBaDssGpgl2AJCbyA+798TWX5q+ooSvWbq/IiL7Gl6fWQXxQJchTQCAfQIKBAtA26CpEHchSSk7KTGMZ3/fFdV011HbR6SwxXWtDugVpCJYD5TGjVnEUSnVQe6EkhrxnviUFbRFENdI0GX4f00pDnoHk5iAbGEAEkgDivgEs1sEuG6hiDUpjYJX5ZOoZLx5dpd1ekaGCNT88wfr2lPGUsky6kl3jszwxkGlo9kkA4SbEARRcyCJKTsi546v8ufLLcBVrNo+qv8PL7OQzRgmnAlbRKGNVjeGVtec7zN7yjMrmgEwKKMsb/khqtS6yvVOHNIFgY690RqA0DY5nQJ2ySaW2Ie8aFYs1Amlwe/E0x1vfDB/MdV21uTUOqmC8lsWQRaB8SH2IupCXoTwJBc+kOtqGuM/C89Nc+uqKmphoqKGDAYgzz1bffvObCJKEpmUgSNrDDx3SwQBsY/woGUF06+Bn5d07N6WsfmamscFq5yi7ySSt2dughOWXn1Gtf0t363fGvWdkOfSDM5z9/HsqlYo6UDCAfr8vYbiL61ZxXVetrbXl3yJ5c6cnSmneZk7u+3Vx+II9BPs/g70GNQEwTgu3ZNIAAAAASUVORK5CYII=",
    "VISC_2": "iVBORw0KGgoAAAANSUhEUgAAACoAAAAcCAYAAAAX4C3rAAADb0lEQVR42u2XS28bVRiGn29udjweK3WcO03aJtAmUaGN2CEisWVT2MGS/8GKHX8ARH9AN0hsKoHYgApdUBatVKhaJAw2IaG52Q6esceeM3NYnNy6BOxCpBxpdDSfjjTPfO973jMjWmtOw7A4JeMM9Az0DPT/CrqzszWUvJNB5Wir1dQ/3P+EqcrP7LamSOUaqVrHsSIyWWDxxTWmp2flPwe98/XH+rUrn+LQBcsl9SpY5JG0jVIRta152ul7XF9d+0ewzr+B+/7el7ob/Qa0eXnpIY6dQaoh62MnDdApZAoHzeLkTzxavwWs8VxBHzy4qxfHP2L0/B4iguTKIAFoDZYHlpi514AD0cqjbWq1qr5wYUGGvpmiKNLV6hMdtu5S9htYohASSGPIBAoVcAsgFugEHB/yZfBnmBjr4HTf55uvbuqherRer+rdzZvMTdYIAk2eXVCdZxe5RVPTmbkfWQAdgVaQZZA0aETjPO1/wPLydRmK9PVfPuP1V+qI2oG0B7kAssRcALZnfHkICZBGIBn0G8YWgGMrkiQejkfDMNTloI701w0MQKqgMAW9pqnlRkEEot4xbNYy0idiamKh7BK25QzHoyJCltkc7QxDAf190920D91diFsGOD8GXgB23vi1MGnqrs+53BYlPuTbO7f0wEF935dmtESqvUN0EBuS0EivUzOrzrFvkxB6LQg3QfVMZ1WMZDFzE00uz96mVqvqge/6K8s3eFi/hnZ88Eqma3buWXAwXlTRkSeRPOCbrmfKrPXGcVyLLFWDj6fJyWnJ3LeJsgnzwM622UCWC+45KCyDXTAv4fpGctNaODix8AKwbFRvjye1l7i0cFmGEvjl8gxxN0exVILeH6AwALYF7JugT0IQF3JlA5v2IGlDvwXOCKHMc//xG6xcfWt4gV+pTLHdKEB6Ij8PvZlGkHRAdUF8sEvgHeRqGpt1SZuNDZ/VV99hbKwiQwMNgkD24zdpdU5KC1osdNo/ToVkm14cE3cOhMudByuHwudpc4lisShDO5lOjnvffaED7zaXput0Yo/H9VUK+QYrcz+isahuzLOf3MB1RxD1OTMTfxJGwubeCitX36VSGX8+oAB7e7t6e/t38vkiFy8uSrPZ0LVfH2HbLrMvLB5J2263dRi2cV33bwMO/Hv07J/ptIH+BVsRhvBq6ucxAAAAAElFTkSuQmCC",
    "ABD_0": "iVBORw0KGgoAAAANSUhEUgAAABsAAAASCAYAAACq26WdAAACr0lEQVR42t2VTW8bZRSFn/vOeMaeGZu4SSYmdSpKwIKKAiqIVsACtvwC/iK/gQ1CID7UCipCAZlYSUyDIhvH8dd4xvO+lw0LNtSGRRac9dE9uvccnSuqynXBcI24VjF/E9JwONTFfEa+zAjCkCCsos6RLRYA1OKYJKnTaDTkWXPkWZ6d9I71afcx+17OtlFELCqChgaxghQWHOTAb6VHnuxx994DoiiSfyX26Nsv9cbVKa1iDMUV6pRyGFCOHXYCfiR4z3lI1WKiDBM3KGpNfrZVbr/1AWm6Jxt51v3lJ22OerSyPm46YPJdSDGsY5cOCUokBCoKsqIcBMx/3MYVU6pyzF03pfvw8809G/R+4M1yjJf0saMmtcMRQXsOUiIoy9MqumyRP91CVwvCfYOEUySc4RWOl0yHJ0eP9c5rb8jazVp+iQmmuKVHdpZiQh97GZF195GqUL01pfbKOfGDHsn9C9S/YvbVAcVJG4lnJMWC8eD39dGfz+caGAVdYWoeXlxSXuxgQqH64oT5MubXvEM/38Hfdfg7S4zx8RrgNTMkAMGhdrX+jHEcy7EV3W28jL3sk7xziVSWYDJsEfJk+jbvffSxnJ2eaP/oE26l50T3TrF5AmUDO03RNKVi65t5Ngu2ybMRDBPKcR0vXGACi6vcIPA8vv7iM7WrnBdqB5R9DyhweYLaABXDRRUOOp3Noj8eX2r34afcwaLDGTpaQMVHjOBCw1l7j3g8ZfePGTiHWgVRJK2T7dTpyTb33/9ws+hvbTXl5qvvciQBxWEKrcZfTEUQ6lGFWuijACIQBXCYMnh+6x+F1jYIwPePvtH56JzIrPBKS2E8llTwxFHTFUZgiUdhYm53Xudmuy3/qa7+jslkos5ZfL9CkiQCMLm6UqeOSiUgjmNZN0P+t//sT1eVO9txVtk2AAAAAElFTkSuQmCC",
    "ABD_1": "iVBORw0KGgoAAAANSUhEUgAAACYAAAAYCAYAAACWTY9zAAADp0lEQVR42u3WS28bZRTG8f955+YZexzHSZ2kSZNULYU2qkAgxG0FYsMn4BPyHVixpRWbFiglLSVNkyaOHcfxZcae23vYsqMlqdRFn/2Rfouj5xxRVd7GGN7SvIO9g73puK87MBwOtX/SJU3GVEWOGAcvqGEchyLPqIocEIIwormwyObWtvwfmLxqXQyHQ/3z4X0axTlrnhKXGWIrEMG6LjYK8JI5WEGtxfqGPh5HmUNz4za3d+7KpcP2n+/p8Mk9bmmJmxwjZkoxiNCywM4K8qkFPLxQwPEQ1yfYPMJEEba6xjhq8bSM+eLr7+TSYN3jY+39+hPvTcc4wSGaZmgVUA4bZC/r4CTk4xKswW94OHUluJpQjGuYIMC/cYaRDRKzwCNZ5MtXxP3n8j/77WduFnOc+j5ZTxn9ssVsbxMTuUjTEN6w1JZj/KZPuBbixT46rzM/jMlO2iQHDegcECU9Nqpznv31RC8M6/d7uu1nONWAyukz72/hdjzkqmXOFmblKrl+gFldxl2OsOcLkK5QFqu4OzXkRoi1bfKjHtI5pZOM6T5/cvG66B6+oFFYpAVV6ULkoc0mVb6IMR7WKmIMWe5gW6vkNWVOThVGqLZxTYhmDtXMIO4Jkk/ws9HFYfk8RfIKo0NqizmmsUc66KJFQZWkZOM+5XyAkFBO++RuD11KyaYjHEewyYxSzgjWa4jjoNbia0WapnqhHouaLTQL0LyJqZ/S+nyK/3JO0eshXpNGsE+pDXaLO5T+IsvFCdfbjynnq+THXcR3aN46xXGmkDSRICZzPKIokgvB1je2GIx2CcOblEcZbntIfWWGhmdIvYGdCg9GO3z47ffU63X5+9lTzQ9+IN7oE7UOoLEIQ0t1eA1lDd1eozwPLt78zYUFeZTHuuyMMadt7GQJZ5Ah0oHDAq2vETeaPP79ASJGs+SclfAO5e4eYudYJ8QmPooHnnA4zrj+/qeX02OTyUT/uPcjd70KOR2j/QQpLXguGMEELuPtKwzE4/pohD0ZI5VFS4tai0Y+phMzvRLzQlb55LOvLqfH4jiWmx9/w8PSp7q9jtlewhqBeQ6zHDuaUZ6nZKVS9ceQ5OisQIsS4hpmZ53ulSYHZu2VUa91K9M01d1HDynGB3RCh5ZVnLwgM8IkrJED9aIkzgtEhDRwGRaWs7LG1q2P2Li2KW/kiP87By/2NZlOsNbiuh5Ro4HneqTplPlshqriBwHt9jLtpaU3+128exTfdtg/p6bY9w2Q4zwAAAAASUVORK5CYII=",
    "ABD_2": "iVBORw0KGgoAAAANSUhEUgAAACwAAAAcCAYAAAAa/l2sAAAEtklEQVR42u3WyW9cWRXH8e+5b6xXg+1yDXZsx5kcRIQIEZt0JMQgdiz4U1mCREssgB5AaaDpJiTBsTuD03a5yq7h1atX7957WLBhAyKi0q2W8luexdVncXR/R1SVb1IM37C8A78DvwO/A//3hKt4JM9z9d4jIhhjsNai6hEEEwQ0Gg352sF/++wvejl4RaQFtRhCAQ9YB/VYaEQGV3kuS8fMBapRi6s3v832lZ3/Cy9v2nR/+uOHaibP2UmEpivgcoKoBad4gWC3DadjqCpAIADJImzWZSARL8uUb919QLvdlrcKHo8v9fM//IY7NUvt4hKjhyAON2qCUfzCo3PB2xRTA4xHqxpqIN17jGk3UH8LKxv8vTJ0b99nZ3dP3hr4w1//Qu8FBWZ8TrB5CO4M++UBy+M21VipLhWXl7hFRdhIiDdTJC2I+pZorYDQEezMEHMLV3R4HMbsfPcnbHY6snLww49+qzeLF9QHJ8j119jDgOr1HlF/ip9GLEdQ27/AXtSx44SoPaO6TIjbU3zVZPakgaQptVuvyO7naHkDN27xUBs8+OnPZeXfWjx5QTbJkRsjlv8oGH9ynfxFwHLYxAUhpBss8w3suIcdB1BtEdW3EL8LmhB1LWHPU+RtlicDTO0JwfyM/WjB8dGhrhT8+NFnuiWKqU8Q/5L5qy3iboNgz2IbDapgl7DfxWW3sZ06slPihzFmEePOMnxyBdtbw7Y2kLRDcVIDsUjvkt5ywenLo9UWx+VoQL0skU4L7xJ81IC1CCtrhOkmQRyxmBaIKoqhCnaxW02KxYKyGVKZAAmbxLFBqiWuDND8HMpn6HSG5qPVgtVVBN6Bn2AyJWweUozPwVn8vMDNS6r5ElssMAbUDqnsELsWo4lQFQVREqK2Yrm4oHbVI2kPrEErj3i72uIQE+HCiGAywGQzWu91CI6fUR47FvMruIXDLwPQOpZzohsWU07weYrKklBSlqNt1BnS3XPSzhKKEUgbqdXQIFotuLm+yZwBce07MB9iWjMa2wWNqx1Uh+j8AuYzpvkuX2Q/Yvv6HV6cHHPl/H366ydIv499/Sm0egSLI0ySomchuv59JFtHytZqwddu3OL4kye05gn29R6ROUNcAa1TxETo4gJMky+iO9z/8c8EYP/adX7/q4FuJVMkPyVigooFqeO+3MKeZFCFjLdDup1rqwVnWSa56WgZjWC6jr7cJIhzAjmFzKDTHlrbp7O+zsOPf6f/WqOAdiZoeA/kBNICP0rQQR3rUryrMLWEo6HjvXsHqy+O+Xyun37wS+6uBbijU8y0QCqPJBFaVogDzSK43ef5UujEkD09g+kCCQQCQZ3DhyHSrmM2mzyLQjoHP6DX76++OLIsk4Pv/ZC/ThzB3X3kagdvPf5iDguHWo9MSvR4xDhoUj4focMZWIeWFs0r1Apma53gzi5PTUi2c++NsW98rU0nE/38zx/RTWb0k5hwOEOHUyiWkEQEN7fINxpk8wL/6BVaLJE4hI0G2m0yEnh+oRzcfUC323u719q/5/x8oEdPH1HlQxJjCQxYLyy9AZOAXxKJJQ4EDywqwaTr7Fw7YHfv6ld7D/+nHc+yTP7X+dcO/irzT+pNX3vLCKapAAAAAElFTkSuQmCC",
}

INDICADORES = [
    {
        "key": "imc",
        "label": "IMC",
        "detalle": "Índice de Masa Corporal (IMC)",
        "suffix": "",
        "decimals": 2,
        "min": 12,
        "max": 50,
        "rangos_h": [
            (12, 18.5, "Bajo", RED, "< 18,5"),
            (18.5, 25, "Normal", PRIMARY, "[ 18,5 - 25 >"),
            (25, 30, "Preobesidad", YELLOW, "[ 25 - 30 >"),
            (30, 50, "Obesidad", YELLOW, ">= 30"),
        ],
        "rangos_m": [
            (12, 18.5, "Bajo", RED, "< 18,5"),
            (18.5, 25, "Normal", PRIMARY, "[ 18,5 - 25 >"),
            (25, 30, "Preobesidad", YELLOW, "[ 25 - 30 >"),
            (30, 50, "Obesidad", YELLOW, ">= 30"),
        ],
        "normal_h": "[ 18,5 - 25 >",
        "normal_m": "[ 18,5 - 25 >",
        "icon_type": "body_gray",
        "invert_trend": True,
    },
    {
        "key": "masa_grasa_pct",
        "label": "Masa grasa (%)",
        "detalle": "Masa grasa (%)",
        "suffix": "%",
        "decimals": 1,
        "min": 0,
        "max": 50,
        "rangos_h": [
            (0, 8, "Déficit", RED, "< 8 %"),
            (8, 20, "Adecuado", PRIMARY, "[ 8 % - 20 % >"),
            (20, 25, "Exceso", YELLOW, "[ 20 % - 25 % >"),
            (25, 50, "Muy Elevado", YELLOW, ">= 25 %"),
        ],
        "rangos_m": [
            (0, 20, "Déficit", RED, "< 20 %"),
            (20, 32, "Adecuado", PRIMARY, "[ 20 % - 32 % >"),
            (32, 38, "Exceso", YELLOW, "[ 32 % - 38 % >"),
            (38, 55, "Muy Elevado", YELLOW, ">= 38 %"),
        ],
        "normal_h": "[ 8 % - 20 % >",
        "normal_m": "[ 20 % - 32 % >",
        "icon_type": "body_orange",
        "invert_trend": True,
    },
    {
        "key": "masa_muscular_pct",
        "label": "Masa muscular (%)",
        "detalle": "Masa Muscular (%)",
        "suffix": "%",
        "decimals": 1,
        "min": 15,
        "max": 55,
        "rangos_h": [
            (15, 33.3, "Bajo", RED, "< 33.3 %"),
            (33.3, 39.4, "Normal", PRIMARY, "[ 33.3 % - 39.40 >"),
            (39.4, 55, "Alto", YELLOW, "<= 39.40 %>"),
        ],
        "rangos_m": [
            (15, 24.3, "Bajo", RED, "< 24.3 %"),
            (24.3, 30.3, "Normal", PRIMARY, "[ 24.3 % - 30.30 >"),
            (30.3, 55, "Alto", YELLOW, "<= 30.30 %>"),
        ],
        "normal_h": "[ 33.3 % - 39.40 >",
        "normal_m": "[ 24.3 % - 30.30 >",
        "icon_type": "muscle",
        "invert_trend": False,
    },
    {
        "key": "grasa_visceral",
        "label": "Grasa visceral",
        "detalle": "Grasa Visceral",
        "suffix": "",
        "decimals": 0,
        "min": 1,
        "max": 30,
        "rangos_h": [
            (1, 9, "Adecuado", PRIMARY, "[ 1 - 9 ]"),
            (9, 14, "Elevado", YELLOW, "[ 10 - 14 ]"),
            (14, 30, "Muy Elevado", YELLOW, "[ 15 - 30 ]"),
        ],
        "rangos_m": [
            (1, 9, "Adecuado", PRIMARY, "[ 1 - 9 ]"),
            (9, 14, "Elevado", YELLOW, "[ 10 - 14 ]"),
            (14, 30, "Muy Elevado", YELLOW, "[ 15 - 30 ]"),
        ],
        "normal_h": "[ 1 - 9 ]",
        "normal_m": "[ 1 - 9 ]",
        "icon_type": "fat_blob",
        "invert_trend": True,
    },
    {
        "key": "perimetro_abdominal",
        "label": "Perímetro Abdominal",
        "detalle": "Perímetro Abdominal (cm)",
        "suffix": " cm",
        "decimals": 1,
        "min": 50,
        "max": 140,
        "rangos_h": [
            (50, 94, "Bajo", PRIMARY, "< 94 cm"),
            (94, 102, "Aumentado", YELLOW, "[ 94 cm - 102 cm ]"),
            (102, 140, "Alto", YELLOW, "> 102 cm"),
        ],
        "rangos_m": [
            (50, 80, "Bajo", PRIMARY, "< 80 cm"),
            (80, 88, "Aumentado", YELLOW, "[ 80 cm - 88 cm ]"),
            (88, 140, "Alto", YELLOW, "> 88 cm"),
        ],
        "normal_h": "< 94 cm",
        "normal_m": "< 80 cm",
        "icon_type": "abdomen",
        "invert_trend": True,
    },
]


def safe_float(value: Any) -> Optional[float]:
    try:
        if value in (None, "", "None", "—"):
            return None
        return float(value)
    except Exception:
        return None


def fmt(value: Any, suffix: str = "", decimals: int = 1) -> str:
    v = safe_float(value)
    if v is None:
        return "—"
    if decimals == 0:
        return f"{v:.0f}{suffix}"
    return f"{v:.{decimals}f}{suffix}"


def calcular_imc(peso: Any, talla_cm: Any) -> Optional[float]:
    p = safe_float(peso)
    t = safe_float(talla_cm)
    if not p or not t:
        return None
    return round(p / ((t / 100) ** 2), 2)


def calcular_edad(fecha_nacimiento: Any) -> Optional[int]:
    if not fecha_nacimiento:
        return None
    try:
        fn = fecha_nacimiento if isinstance(fecha_nacimiento, date) else date.fromisoformat(str(fecha_nacimiento)[:10])
        hoy = date.today()
        return hoy.year - fn.year - ((hoy.month, hoy.day) < (fn.month, fn.day))
    except Exception:
        return None


def sexo_key(sexo: Any) -> str:
    s = str(sexo or "").strip().lower()
    return "m" if s.startswith("f") else "h"


def _rangos(ind: Dict[str, Any], sexo: Any) -> List[Tuple[float, float, str, str, str]]:
    return ind["rangos_m"] if sexo_key(sexo) == "m" else ind["rangos_h"]


def clasificar(ind: Dict[str, Any], valor: Any, sexo: Any) -> str:
    v = safe_float(valor)
    if v is None:
        return "—"
    rangos = _rangos(ind, sexo)
    for desde, hasta, label, _color, _txt in rangos:
        if desde <= v < hasta or (v == hasta and hasta == ind.get("max")):
            return label
    return rangos[-1][2]


def tendencia(valor_actual: Any, valor_anterior: Any, invertir: bool = False) -> str:
    a = safe_float(valor_actual)
    b = safe_float(valor_anterior)
    if a is None or b is None:
        return ""
    if abs(a - b) < 0.01:
        return "→"
    mejora = a < b if invertir else a > b
    return "▲" if mejora else "▼"


def logo_to_data_uri(uploaded_file: Any) -> Optional[str]:
    if not uploaded_file:
        return None
    raw = uploaded_file.getvalue()
    mime = getattr(uploaded_file, "type", None) or "image/png"
    return f"data:{mime};base64,{base64.b64encode(raw).decode('utf-8')}"


def _eval_value(ind_key: str, medicion: Dict[str, Any]) -> Any:
    if not medicion:
        return None
    if ind_key == "perimetro_abdominal":
        return medicion.get("perimetro_abdominal") or medicion.get("perimetro_cintura") or medicion.get("circ_cintura")
    if ind_key == "imc":
        return medicion.get("imc") or calcular_imc(medicion.get("peso"), medicion.get("talla"))
    return medicion.get(ind_key)


def _tiene_metricas(medicion: Dict[str, Any]) -> bool:
    if not isinstance(medicion, dict):
        return False
    for ind in INDICADORES:
        if safe_float(_eval_value(ind["key"], medicion)) is not None:
            return True
    return False


def build_composicion_payload(
    *,
    paciente: Dict[str, Any],
    mediciones: List[Dict[str, Any]],
    medicion_actual: Dict[str, Any],
    logo_dueno: Optional[str] = None,
    logo_empresa: Optional[str] = None,
    notas: str = "",
) -> Dict[str, Any]:
    meds = [dict(m) for m in (mediciones or []) if isinstance(m, dict)]
    meds = sorted(meds, key=lambda m: (str(m.get("fecha_medicion") or m.get("fecha_registro") or ""), int(m.get("version") or 0)))

    med_act = dict(medicion_actual or {})

    # Si la app no manda una medición actual explícita, usamos la última
    # medición real del historial. Así la plantilla no queda en guiones cuando
    # ya existen Evaluación 1 / 2 / 3 / 4 en historia_nutricional.
    if not _tiene_metricas(med_act) and meds:
        med_act = dict(meds[-1])

    med_act["imc"] = med_act.get("imc") or calcular_imc(med_act.get("peso"), med_act.get("talla"))
    med_act["perimetro_abdominal"] = (
        med_act.get("perimetro_abdominal")
        or med_act.get("perimetro_cintura")
        or med_act.get("circ_cintura")
    )

    if med_act and not any(str(m.get("version")) == str(med_act.get("version")) and str(m.get("fecha_registro") or m.get("fecha_medicion")) == str(med_act.get("fecha_registro") or med_act.get("fecha_medicion")) for m in meds):
        meds.append(med_act)

    meds = sorted(meds, key=lambda m: (str(m.get("fecha_medicion") or m.get("fecha_registro") or ""), int(m.get("version") or 0)))[-4:]

    return {
        "tipo": "composicion_corporal",
        "template_key": "reto_saludable_composicion_v3_fiel_pdf_html",
        "fecha_generacion": str(date.today()),
        "logos": {"dueno": logo_dueno, "empresa": logo_empresa},
        "paciente": {
            "id_paciente": paciente.get("id_paciente"),
            "nombre": paciente.get("nombre"),
            "apellido": paciente.get("apellido"),
            "nombre_completo": f"{paciente.get('nombre','')} {paciente.get('apellido','')}".strip(),
            "dni": paciente.get("dni"),
            "email": paciente.get("email"),
            "sexo": med_act.get("sexo") or paciente.get("genero"),
            "edad": med_act.get("edad") or calcular_edad(paciente.get("fecha_nacimiento")),
            "empresa": paciente.get("empresa"),
            "tipo_paciente": paciente.get("tipo_paciente"),
        },
        "medicion_actual": med_act,
        "evaluaciones": meds,
        "notas": notas or med_act.get("notas") or "",
    }


def _esc(x: Any) -> str:
    return escape(str(x if x not in (None, "") else "—"))


def _pct(ind: Dict[str, Any], value: Any) -> float:
    v = safe_float(value)
    mn, mx = float(ind["min"]), float(ind["max"])
    if v is None:
        return 0.0
    return max(0.0, min(100.0, (v - mn) / (mx - mn) * 100.0))


def _bar_summary_html(ind: Dict[str, Any], valor: Any, sexo: Any) -> str:
    """Barra superior: si no hay dato, queda en blanco. Si hay dato, muestra rangos + marcador."""
    v = safe_float(valor)
    if v is None:
        return "<div class='mini-bar mini-empty'></div>"
    mn, mx = float(ind["min"]), float(ind["max"])
    segs = []
    ticks = []
    for desde, hasta, label, color, _txt in _rangos(ind, sexo):
        left = max(0, min(100, (desde - mn) / (mx - mn) * 100))
        width = max(0, min(100 - left, (hasta - desde) / (mx - mn) * 100))
        segs.append(f"<span class='mini-seg' style='left:{left:.3f}%;width:{width:.3f}%;background:{color}'></span>")
        ticks.append(f"<span class='mini-tick' style='left:{left:.3f}%'>{_esc(desde if desde % 1 else int(desde))}</span>")
    ticks.append(f"<span class='mini-tick' style='left:98%'>{_esc(int(mx) if mx % 1 == 0 else mx)}</span>")
    return f"""
    <div class='mini-bar'>
      {''.join(segs)}
      {''.join(ticks)}
      <span class='mini-marker' style='left:{_pct(ind, v):.3f}%'></span>
    </div>
    """


def _detail_scale_html(ind: Dict[str, Any], valor: Any, sexo: Any) -> str:
    v = safe_float(valor)
    if v is None:
        return "<div class='detail-scale empty-scale'></div>"
    mn, mx = float(ind["min"]), float(ind["max"])
    segs = []
    for desde, hasta, label, color, _txt in _rangos(ind, sexo):
        left = max(0, min(100, (desde - mn) / (mx - mn) * 100))
        width = max(0, min(100 - left, (hasta - desde) / (mx - mn) * 100))
        segs.append(f"<span style='left:{left:.3f}%;width:{width:.3f}%;background:{color}'><em>{_esc(label)}</em></span>")
    return f"""
      <div class='detail-scale'>
        {''.join(segs)}
        <i style='left:{_pct(ind, v):.3f}%'></i>
      </div>
    """


def _icon_svg(icon_type: str, idx: int) -> str:
    """Iconos tomados de la referencia original, no dibujados a mano.

    Se usan como pictogramas estáticos por categoría; lo dinámico sigue siendo:
    valores, clasificación activa, color de la categoría y gráficos superiores.
    """
    if icon_type == "body_gray":
        key = f"IMC_{min(idx, 3)}"
        cls = "ico-img imc-img"
    elif icon_type == "body_orange":
        key = f"FAT_{min(idx, 3)}"
        cls = "ico-img fat-img"
    elif icon_type == "muscle":
        key = f"MUSCLE_{min(idx, 2)}"
        cls = "ico-img muscle-img"
    elif icon_type == "fat_blob":
        key = f"VISC_{min(idx, 2)}"
        cls = "ico-img visc-img"
    else:
        key = f"ABD_{min(idx, 2)}"
        cls = "ico-img abdomen-img"

    return f"<img class='{cls} icon-{idx}' src='data:image/png;base64,{ICON_B64[key]}' />"

def _detail_categories_html(ind: Dict[str, Any], valor: Any, sexo: Any) -> str:
    v = safe_float(valor)
    current = clasificar(ind, v, sexo) if v is not None else None
    rangos = _rangos(ind, sexo)
    icons = "".join(f"<div class='icon-cell'>{_icon_svg(ind['icon_type'], i)}</div>" for i in range(len(rangos)))
    boxes = []
    for _desde, _hasta, label, _color, txt in rangos:
        active = " active" if current == label else ""
        boxes.append(f"<div class='cat{active}'><b>{_esc(label)}</b><span>{_esc(txt)}</span></div>")
    return f"""
    <div class='detail-icons cols-{len(rangos)}'>{icons}</div>
    <div class='detail-cats cols-{len(rangos)}'>{''.join(boxes)}</div>
    """


def _fmt_tick(x: Any) -> str:
    v = safe_float(x)
    if v is None:
        return ""
    if abs(v - int(v)) < 0.0001:
        return str(int(v))
    return str(v).replace(".", ",")


def _mini_headers(ind: Dict[str, Any], sexo: Any) -> str:
    """Números superiores de corte para la tabla principal."""
    v = []
    for desde, hasta, _label, _color, _txt in _rangos(ind, sexo):
        v.append(desde)
    v.append(_rangos(ind, sexo)[-1][1])
    mn, mx = float(ind["min"]), float(ind["max"])
    ticks = []
    for x in v[1:]:
        pos = max(0, min(100, (float(x) - mn) / (mx - mn) * 100))
        ticks.append(f"<span class='mini-tick' style='left:{pos:.3f}%'>{_esc(_fmt_tick(x))}</span>")
    return "".join(ticks)


def _bar_summary_html(ind: Dict[str, Any], valor: Any, sexo: Any) -> str:
    """Barra superior: sin dato queda blanca; con dato muestra rangos + marcador dinámico."""
    v = safe_float(valor)
    if v is None:
        return "<div class='mini-bar mini-empty'></div>"
    mn, mx = float(ind["min"]), float(ind["max"])
    segs = []
    for desde, hasta, _label, color, _txt in _rangos(ind, sexo):
        left = max(0, min(100, (desde - mn) / (mx - mn) * 100))
        width = max(0, min(100 - left, (hasta - desde) / (mx - mn) * 100))
        segs.append(f"<span class='mini-seg' style='left:{left:.3f}%;width:{width:.3f}%;background:{color}'></span>")
    return f"""
    <div class='mini-bar'>
      {''.join(segs)}
      {_mini_headers(ind, sexo)}
      <span class='mini-marker' style='left:{_pct(ind, v):.3f}%'></span>
    </div>
    """


def render_composicion_html(payload: Dict[str, Any]) -> str:
    pac = payload.get("paciente", {})
    med = payload.get("medicion_actual", {})
    evals = (payload.get("evaluaciones", []) or [])[-4:]
    sexo = pac.get("sexo") or med.get("sexo")
    logos = payload.get("logos", {}) or {}

    logo_left = f"<img src='{logos.get('dueno')}' class='logo logo-left'>" if logos.get("dueno") else "<div class='logo-ph'>LOGO</div>"
    logo_right = f"<img src='{logos.get('empresa')}' class='logo logo-right'>" if logos.get("empresa") else "<div class='logo-ph logo-right'>EMPRESA</div>"
    body_img = f"data:image/png;base64,{BODY_SILHOUETTE_B64}"

    # Orden de evaluaciones: la medición actual aparece reflejada como última evaluación disponible.
    summary_rows = []
    detail_blocks = []

    for idx, ind in enumerate(INDICADORES, 1):
        val = _eval_value(ind["key"], med)
        normal_txt = ind["normal_m"] if sexo_key(sexo) == "m" else ind["normal_h"]
        eval_cells = []
        for i in range(4):
            if i < len(evals):
                ev_val = _eval_value(ind["key"], evals[i])
                prev_val = _eval_value(ind["key"], evals[i - 1]) if i > 0 else None
                tr = tendencia(ev_val, prev_val, invertir=ind.get("invert_trend", False)) if i > 0 else ""
                tr_html = f"<span class='trend'>{tr}</span>" if tr else ""
                eval_cells.append(f"<td>{fmt(ev_val, '', ind['decimals'])}{tr_html}</td>")
            else:
                eval_cells.append("<td>--</td>")

        summary_rows.append(f"""
        <tr>
          <th>{_esc(ind['label'])}</th>
          <td class='range-cell'>{_bar_summary_html(ind, val, sexo)}</td>
          <td class='normal'>{_esc(normal_txt)}</td>
          {''.join(eval_cells)}
        </tr>
        """)

        value_box = fmt(val, ind["suffix"], ind["decimals"])
        detail_blocks.append(f"""
        <section class='metric-block'>
            <div class='metric-title'>{idx}. {_esc(ind['detalle'])}: <span>{value_box}</span></div>
            {_detail_categories_html(ind, val, sexo)}
        </section>
        """)

    return f"""
<!doctype html>
<html>
<head>
<meta charset='utf-8'>
<style>
@page {{ size: 794px 1123px; margin: 0; }}
* {{ box-sizing: border-box; }}
html, body {{ margin: 0; padding: 0; background: #fff; }}
body {{ font-family: Arial, Helvetica, sans-serif; color: {DARK}; }}
.sheet {{ width: 794px; height: 1123px; margin: 0 auto; padding: 24px 22px 20px 22px; background: #fff; overflow: hidden; }}
.top {{ display: grid; grid-template-columns: 110px 1fr 110px; align-items: start; height: 78px; }}
.logo {{ max-width: 90px; max-height: 60px; object-fit: contain; }}
.logo-right {{ justify-self: end; }}
.logo-ph {{ width: 88px; height: 44px; border: 1px dashed #C9D0D0; color: #9B84B7; font-size: 10px; display:flex; align-items:center; justify-content:center; }}
.title {{ text-align: center; padding-top: 8px; }}
.title h1 {{ margin: 0; color: {PRIMARY}; font-size: 22px; line-height: 1; font-weight: 900; letter-spacing: .3px; }}
.title p {{ margin: 5px 0 0; font-size: 13px; color: #777; font-weight: 700; }}
.meta {{ display:grid; grid-template-columns: 175px 175px 175px; justify-content: space-between; margin: 0 0 14px; }}
.pill {{ display:grid; grid-template-columns: 78px 1fr; height: 25px; border:1px solid #8DB1B1; }}
.pill b {{ background:{PRIMARY}; color:white; display:flex; align-items:center; justify-content:center; font-size:11px; }}
.pill span {{ background:{CYAN}; display:flex; align-items:center; justify-content:center; font-size:12px; color:#667; }}
.patient-name {{ text-align:center; font-size:12px; color:#777; font-weight:800; margin: 0 0 7px; }}
.summary {{ width: 100%; border-collapse: collapse; table-layout: fixed; margin-bottom: 16px; }}
.summary th, .summary td {{ border: 1px solid {BORDER}; height: 25px; padding: 0; text-align:center; vertical-align:middle; font-size:9px; line-height:1; }}
.summary thead th {{ background:#F2F6F6; color:#666; font-weight:800; }}
.summary thead .hdr-bajo {{ color:#FF6262; }}
.summary thead .hdr-est {{ color:{PRIMARY}; }}
.summary thead .hdr-alto {{ color:{YELLOW}; }}
.summary tbody th {{ background:{CYAN}; color:#687878; font-weight:800; }}
.range-cell {{ padding: 0 4px !important; }}
.normal {{ background:{CYAN}; color:#607070; font-weight:800; }}
.trend {{ color:#008860; font-weight:900; padding-left:3px; font-size:8px; }}
.mini-bar {{ position: relative; height: 12px; border: 1px solid #333; background: white; overflow: visible; margin: 12px 2px 1px; }}
.mini-empty {{ border-color: #BFCACA; background: #fff; }}
.mini-seg {{ position:absolute; top:0; bottom:0; }}
.mini-marker {{ position:absolute; top:-5px; height:22px; width:2px; background:#333; border-radius:1px; z-index:4; }}
.mini-tick {{ position:absolute; top:-15px; transform:translateX(-50%); font-size:4.7px; color:#565656; line-height:1; background:#fff; padding:0 1px; z-index:5; }}
.content {{ display:grid; grid-template-columns: 430px 285px; column-gap: 18px; align-items:start; }}
.metrics {{ padding-top: 0; }}
.metric-block {{ margin-bottom: 14px; min-height: 128px; }}
.metric-title {{ font-size:12.5px; font-weight:900; color:#666; margin: 0 0 6px; white-space:nowrap; }}
.metric-title span {{ display:inline-block; min-width: 84px; text-align:center; margin-left:14px; padding: 5px 10px; background:{CYAN}; color:#607070; font-weight:900; }}
.detail-icons, .detail-cats {{ display:grid; width: 315px; margin-left: 92px; align-items:end; }}
.detail-icons.cols-3, .detail-cats.cols-3 {{ grid-template-columns: repeat(3, 1fr); }}
.detail-icons.cols-4, .detail-cats.cols-4 {{ grid-template-columns: repeat(4, 1fr); }}
.icon-cell {{ height: 66px; display:flex; align-items:end; justify-content:center; overflow: visible; }}
.ico-img {{ display:block; object-fit:contain; image-rendering:auto; }}
.imc-img {{ height:58px; width:auto; }}
.imc-img.icon-0 {{ height:58px; }}
.imc-img.icon-1 {{ height:58px; }}
.imc-img.icon-2 {{ height:58px; }}
.imc-img.icon-3 {{ height:58px; }}

.fat-img {{ height:62px; width:auto; }}
.fat-img.icon-0 {{ height:62px; }}
.fat-img.icon-1 {{ height:62px; }}
.fat-img.icon-2 {{ height:62px; }}
.fat-img.icon-3 {{ height:62px; }}

.muscle-img {{ width:auto; height:34px; margin-bottom:7px; }}
.muscle-img.icon-0 {{ height:27px; }}
.muscle-img.icon-1 {{ height:32px; }}
.muscle-img.icon-2 {{ height:38px; }}

.visc-img {{ width:auto; height:30px; margin-bottom:7px; }}
.visc-img.icon-0 {{ height:20px; }}
.visc-img.icon-1 {{ height:26px; }}
.visc-img.icon-2 {{ height:32px; }}

.abdomen-img {{ width:auto; height:34px; margin-bottom:5px; }}
.abdomen-img.icon-0 {{ height:24px; }}
.abdomen-img.icon-1 {{ height:30px; }}
.abdomen-img.icon-2 {{ height:36px; }}
.cat {{ height: 35px; background:#D9D9D9; color:#6B6B6B; display:flex; flex-direction:column; align-items:center; justify-content:center; font-size:10px; line-height:1.05; border-right:1px solid #F2F2F2; }}
.cat b {{ font-size:10.5px; font-weight:900; }}
.cat span {{ font-size:9.5px; margin-top:3px; }}
.cat.active {{ background:{YELLOW}; color:#fff; }}
.body-area {{ display:flex; justify-content:center; align-items:flex-start; padding-top: 0; overflow: visible; }}
.body-img {{ width: 285px; height: 690px; object-fit: contain; display:block; }}
</style>
</head>
<body>
<div class='sheet'>
    <div class='top'>
        <div>{logo_left}</div>
        <div class='title'><h1>RETO SALUDABLE</h1><p>Análisis de Composición Corporal</p></div>
        <div>{logo_right}</div>
    </div>

    <div class='meta'>
        <div class='pill'><b>DNI</b><span>{_esc(pac.get('dni'))}</span></div>
        <div class='pill'><b>Sexo</b><span>{_esc(pac.get('sexo'))}</span></div>
        <div class='pill'><b>Edad</b><span>{_esc(pac.get('edad'))}</span></div>
    </div>

    <div class='patient-name'>{_esc(pac.get('nombre_completo'))}</div>

    <table class='summary'>
      <colgroup>
        <col style='width:120px'><col style='width:270px'><col style='width:85px'>
        <col style='width:68px'><col style='width:68px'><col style='width:68px'><col style='width:68px'>
      </colgroup>
      <thead>
        <tr>
          <th></th>
          <th><span class='hdr-bajo'>Bajo</span> / <span class='hdr-est'>Estándar</span> / <span class='hdr-alto'>Alto</span></th>
          <th>Normal</th>
          <th>Evaluación 1</th><th>Evaluación 2</th><th>Evaluación 3</th><th>Evaluación 4</th>
        </tr>
      </thead>
      <tbody>{''.join(summary_rows)}</tbody>
    </table>

    <div class='content'>
        <div class='metrics'>{''.join(detail_blocks)}</div>
        <div class='body-area'><img class='body-img' src='{body_img}'></div>
    </div>
</div>
</body>
</html>
"""


def show_composicion_preview(payload: Dict[str, Any], height: int = 1120):
    # La plantilla mide 794x1123px (A4 a 96dpi). Se deja scroll para que Streamlit no la corte.
    components.html(render_composicion_html(payload), height=height, scrolling=True)


def _img_from_data_uri(data_uri: Optional[str], max_w: float, max_h: float):
    if not data_uri:
        return Paragraph("", ParagraphStyle("empty", fontSize=1))
    try:
        raw_b64 = data_uri.split(",", 1)[1]
        bio = io.BytesIO(base64.b64decode(raw_b64))
        img = Image(bio)
        img._restrictSize(max_w, max_h)
        return img
    except Exception:
        return Paragraph("", ParagraphStyle("empty", fontSize=1))


def _body_reportlab(max_w: float, max_h: float):
    bio = io.BytesIO(base64.b64decode(BODY_SILHOUETTE_B64))
    img = Image(bio)
    img._restrictSize(max_w, max_h)
    return img


def _p(text: Any, style: ParagraphStyle) -> Paragraph:
    return Paragraph(escape(str(text if text not in (None, "") else "—")), style)


def _buscar_navegador_local():
    """Busca Chrome/Chromium/Edge en Windows y Linux."""
    candidatos = [
        os.environ.get("CHROME_PATH"),
        os.environ.get("CHROMIUM_PATH"),

        # Streamlit Cloud / Linux
        "/usr/bin/chromium",
        "/usr/bin/chromium-browser",
        "/usr/bin/google-chrome",
        "/usr/bin/google-chrome-stable",

        # Windows local
        r"C:\Program Files\Google\Chrome\Application\chrome.exe",
        r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
        r"C:\Program Files\Microsoft\Edge\Application\msedge.exe",
        r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
    ]

    for path in candidatos:
        if path and os.path.exists(path):
            return path

    return None


async def _html_to_pdf_async(html: str) -> bytes:
    from pyppeteer import launch

    navegador = _buscar_navegador_local()
    if not navegador:
        raise RuntimeError(
            "No encontré Chrome ni Edge instalado para generar el PDF. "
            "Instalá Google Chrome o configurá la variable CHROME_PATH con la ruta de chrome.exe."
        )

    browser = await launch(
        executablePath=navegador,
        headless=True,
        args=[
            "--no-sandbox",
            "--disable-setuid-sandbox",
            "--disable-dev-shm-usage",
            "--disable-gpu",
        ],
        handleSIGINT=False,
        handleSIGTERM=False,
        handleSIGHUP=False,
    )
    try:
        page = await browser.newPage()
        await page.setViewport({"width": 794, "height": 1123, "deviceScaleFactor": 1})
        # pyppeteer 2.0 no acepta waitUntil en setContent().
        # Cargamos el HTML y esperamos brevemente a que el navegador pinte estilos/inline SVG.
        await page.setContent(html)
        await page.waitFor(300)
        try:
            await page.emulateMedia("screen")
        except TypeError:
            await page.emulateMedia(mediaType="screen")
        pdf = await page.pdf({
            "printBackground": True,
            "width": "794px",
            "height": "1123px",
            "margin": {"top": "0px", "right": "0px", "bottom": "0px", "left": "0px"},
            "preferCSSPageSize": True,
        })
        return pdf
    finally:
        await browser.close()


def _run_async_pdf(html: str) -> bytes:
    loop = asyncio.new_event_loop()
    try:
        asyncio.set_event_loop(loop)
        return loop.run_until_complete(_html_to_pdf_async(html))
    finally:
        asyncio.set_event_loop(None)
        loop.close()


def build_composicion_pdf(payload: Dict[str, Any]) -> bytes:
    html = render_composicion_html(payload)
    return _run_async_pdf(html)